### ISSUE TITLE
Clarification of Transaction details cluster content

### ISSUE THREAD

**Issue by BH-UDA** [ConsumerDataStandardsAustralia/standards#100]
We are seeking clarification on the provision of data relating to Payer and Payee within the Transaction Detail cluster of the Consumer Data and the associated Data Language Standards. 
The BankingTransaction schema describes payer content as "Label of the originating payer. Mandatory for inbound payment." and payee as "Label of the target PayID. Mandatory for an outbound transaction. "The name assigned to the BSB/Account number or PayID" (by the owner of the PayID)".
In contrast the Data Language section of the Consumer Experience Guidelines includes the following permission language "Who you have sent money to and received money from; (e.g. their name, BSB, account number)".
It would appear the Data Language Standards may be misleading as the provision of BSB and Account number of a payee or payer associated to a transaction may contravene privacy standards. Can the requirements in relation to payee and payer information be clarified (e.g. Is BSB and account number permitted/required? What is specific requirement? Is masking of information required?) and can the Data Language requirement be reviewed/amended to clarify?

**Comment by CDR-API-Stream** [comment]
Hi @BH-UDA, thank you for this question.  Queries and change requests are being addressed in the [Maintenance Repository](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance).  It would be appreciated if you could repost your question there and the DSB will respond to it.

**Comment by CDR-API-Stream** [comment]
Thanks
