### ISSUE TITLE
Documentation Update: Non normative example for Request Object needs to list the mandatory claim exp

### ISSUE THREAD

**Issue by CDR-AMO** [ConsumerDataStandardsAustralia/standards#104]
The non-normative example for Request Object at https://consumerdatastandardsaustralia.github.io/standards/#request-object needs to list the mandatory claim exp. Referring to Section 5.2.2 of FAPI-RW at https://openid.net/specs/openid-financial-api-part-2.html#authorization-server, it is specified that exp claim must be present in the Authorization Request Object. 

Following is the non-normative example for Request Object on the CDR Standards Page and needs to include the exp claim:
Non-Normative Example - acr as an Essential Claim
#Decoded Request Object JWT

{
  "alg": "PS256",
  "typ": "JWT",
  "kid": "123"
}
{
  "aud": "https://www.recipient.com.au",
  "response_type": "code id_token",
  "client_id": "12345",
  "redirect_uri": "https://www.recipient.com.au/coolstuff",
  "scope": "openid",
  "state": "af0ifjsldkj",
  "nonce": "n-0S6_WzA2Mj",
  "claims": {
    "sharing_duration": 7776000,
    "id_token": {
      "acr": {
        "essential": true,
        "values": ["urn:cds.au:cdr:3"]
      }
    },
    "userinfo": {
      "given_name": null,
      "family_name": null
    }
  }
}

**Comment by CDR-API-Stream** [comment]
Thanks very much for raising this issue.  It is in fact a documentation defect and will be updated in the next standards update.

For future reference, items of this nature should be raised as a change request on the standards maintenance site that can be reached at the following link:
https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues

The DSB will raise an issue with the above content to close the loop on this issue.
