### ISSUE TITLE
Decision Proposal 110 - Additional Account Holders

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#110]
The decision proposal for Additional Account Holders is attached below:
[Decision Proposal 110 - Additional Account Holders.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/4768776/Decision.Proposal.110.-.Additional.Account.Holders.pdf)

Note that this proposal contains no recommendation.  It is seeking information from community participants that will assist in the creation of subsequent proposals.

Feedback is very welcome on this proposal. This thread will remain open for feedback until the 3rd of July.

As previously discussed in various forums, the practice of the DSB is to respond to feedback incrementally before the consultation is complete to promote an interactive style of consultation.
Participants are therefore encouraged to provide feedback earlier in the consultation process so that the community can work together to a consensus outcome.

**Comment by SelenaLiuEA** [comment]
Hi All, 

These are EnergyAustralia's initial comments. Our comments only provide information to inform the DSB as to how Additional Account Holders might be structured in the energy sector. We note that different retailers are likely to have different arrangements. This response has the purpose of informing data specifications about account, billing and customer data clusters. We reserve our views on how the concept of a CDR consumer may extend to Additional Account Holders as that is not the focus of the DSB’s proposal. 

EnergyAustralia’s Additional Account Holder arrangements are aligned with the “Authorised Contact” arrangement described in the DSB’s proposal. This involves a “Primary Account Holder” who is the Customer buying energy under the contract with the energy retailer, and the assignment of Additional Account Holders to the Customer’s account (with consent of both parties required for some authorisations). In contrast to joint accounts in the banking sector where the joint account holder is receiving the same service as the Customer, energy retailers may not be providing Additional Account Holders the same energy service that they are providing the Customer (although it would be common that this would be the case). 

We also note that while the Additional Account Holder is not a Customer under this arrangement, it is possible to have Additional Account Holders associated with an account that have the ability to do almost everything a Customer can do with their account. This type of Additional Account Holder is also held “financially responsible” or accountable for any debt that may incur on the account. A description of this type of Additional Account Holder and other types with a lower level of authority is set out in EnergyAustralia’s post on this steam:  https://github.com/ConsumerDataStandardsAustralia/standards/issues/106  

From a data structure perspective:
•	An account will have one Customer (primary account holder) but can have multiple Additional Account Holders.
•	Additional Account Holders are treated as attributes on an account.

Cheers, 
Selena

**Comment by CDR-API-Stream** [comment]
This consultation will be extended by a week to obtain more retailer feedback

**Comment by CDR-API-Stream** [comment]
This consultation is now being closed.  In the absence of additional public contribution we will develop the initial position assuming that the contribution from EnergyAustralia is generally indicative of other retailers.
