### ISSUE TITLE
Decision Proposal 117 - Distributed Energy Resources Payload

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#117]
The decision proposal for Distributed Energy Resources data is attached below:
[Decision Proposal 117 - Distributed Energy Resources Payloads.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/5520603/Decision.Proposal.117.-.Distributed.Energy.Resources.Payloads.pdf)

The structures contained in this proposal are based on the data held by AEMO in the DER Register that they maintain.  AEMO is the sole designated data holder for these data sets.

Feedback is welcome on this proposal. This thread will remain open for feedback until the 27th of November.

**Comment by DSB-Rob** [comment]
For those interested in the Electricity / Energy Sector, please be advised that the Treasury is now seeking views on the draft CDR designation instrument.

https://treasury.gov.au/consultation/consumer-data-right-energy-sector-designation-instrument

**Comment by SelenaLiuEA** [comment]
Good afternoon All, 

EnergyAustralia’s comments on the DER register payloads are that the following fields are key and should be mandatory where a value can be returned. They are also data points which in our experience customers find difficult locating.  

- protectionMode - exportLimitkva 
- acConnections – equipmentType, manufacturerName, InverterSeries, inverterModelNumber, commissioningDate, installationStage, status, inverterDeviceCapacity. In particular, manufacturerName and inverterSeries would assist with VPP eligibility identification. 
- derDevices – count, manufacturer, modelNumber, status, installationStage, type, nominalRatedCapacity, nominalStorageCapacity

Other specific comments below: 
- approvedCapacity - There should be a capacity for each technology (example, a 5 kVA battery inverter and 5kVA solar inverter which are coupled through an AC bus behind the meter) and having this information split out would be useful. Perhaps this should say, "approved capacity for technology one" and another field, "approved capacity for technology 2", and another string field saying "technology type 1" (example response "PV") and "technology type 2" (example response "storage - Lithium ION"). This would appear to be the intent of how the payloads should operate – but we wish to confirm this outcome. 
- InstalledPhasesCount – Does this account for all inverter/asset combinations? E.g. a 3 phase solar inverter coupled with a single phase battery.
- exportLimitkva – Some distributors allow export from one technology type (e.g. solar PV) but not others (e.g. battery). Similar to approvedCapacity, we wish to confirm that different technologies can be split out.  
- derDevices – refers to count which means Number of devices in the group of DER devices, we again raise the point around the splitting out of different technologies under derDevices (for data points that are not common between technologies). 

Happy to clarify if any of the above is unclear. 

Thanks 
Selena

**Comment by CDR-API-Stream** [comment]
Thanks for the feedback Selena.  We will validate the feedback with AEMO to determine if they hold the data to accommodate the suggestions made.

**Comment by CDR-API-Stream** [comment]
Feedback on this consultation will now be closed.
