### ISSUE TITLE
Decision Proposal 122 - Extension of Supported HTTP Response Codes for Enhanced Error Handling

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#122]
This issue pertains to consultation on CDR Error Codes catalogue to cater for [Enhanced Error Handling](#68).

Specifically, this decision proposal is seeking to address whether additional HTTP Response Codes, not currently described, should be included in the Data Standards's [HTTP Response Code section](https://consumerdatastandardsaustralia.github.io/standards/#http-response-codes). 

**Note** that this will only seek to address aspects of the standards where error handling is not already covered by normative references (such as OIDC).

The consultation draft Decision Proposal has been attached below:
[Decision Proposal 122 - Enhanced Error Handling - Introduction of New HTTP Response Codes.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/4720082/Decision.Proposal.122.-.Enhanced.Error.Handling.-.Introduction.of.New.HTTP.Response.Codes.pdf)

Feedback is now opened for this proposal. Feedback is planned to close on the 10th July 2020.

---

As part of the Enhanced Error Handling consultation a Working Group workshop series has now been set up. To register for the second workshop covering #121 and #122, please register your interest here: https://dsb_enhancederrors_workshop02.eventbrite.com.au

**Comment by perlboy** [comment]
As stated in https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/174 the use of 404 is normal REST but is not allowed in the UK specifications for reasons outlined in 174. The lack of 404 was an outcome of #11

**Comment by CDR-API-Stream** [comment]
The draft decision proposal for this issue has been posted in the issue description.

A working group meeting series to cover this and the other aspects of Enhanced Error Handling will be set up to walk through the decision proposals. Details will be posted in this issue thread when they are available.

**Comment by CDR-API-Stream** [comment]
As part of the Enhanced Error Handling consultation a Working Group workshop series has now been set up. To register for the second workshop covering #121 and #122, please register your interest here: https://dsb_enhancederrors_workshop02.eventbrite.com.au

**Comment by AElharouny** [comment]
Hello, 
I was hoping for more clarification on the disadvantages of option 3:
```
Disadvantages
• Change for implementations today because it's describing new scenarios not existing
scenarios
```

**Comment by NationalAustraliaBank** [comment]
Due to this decision proposal’s feedback period is coinciding with go-live activities, NAB requests that the decision proposal remain open for feedback until July 24th.

**Comment by mannharleen** [comment]
## Feedback from Origin Energy on DP-122
We favor the current recommendation of DSB to go with Option-3

**Comment by AElharouny** [comment]
AGL Energy feedback

We do agree to using  `404 Not Found` for the 3 cases provided (recommendation) and we want to draw Data Standards Body attention to one of the security principles followed by many APIs which is to return HTTP status code `404 Not Found` if a client requests a resource that exists, but that they are not authorised to access to avoid leaking information about other customers data.

The reasoning behind that is: if you don't have permission on a record, you shouldn't be able to confirm if that record exists.

**Comment by commbankoss** [comment]
Commonwealth Bank recommends the adoption of Option 3 for Decision Proposal 122. This option aligns best with RESTful API standards, and adds more clarity with the addition of 404 for the described scenarios.

**Comment by CDR-API-Stream** [comment]
Hi @NationalAustraliaBank, consultation on this decision proposal will be extended until 10th July. Feedback received in this and the related enhanced error handling DPs will be reviewed and updated DPs provided for review accordingly.

**Comment by CDR-API-Stream** [comment]
> Hello,
> I was hoping for more clarification on the disadvantages of option 3:
> 
> ```
> Disadvantages
> • Change for implementations today because it's describing new scenarios not existing
> scenarios
> ```

Hi @AElharouny, the implication of Option 3 is that any existing DH implementations will require change if they do not respond with a 404 Not Found when a resource identifier is provided in the URL. Rather than a disadvantage, it is probably more correctly a consideration of the option and a consequence of aligning for consistency. As part of the transition plan this would need to be considered along with other aspects where the standards seek to define greater consistency and uniformity.

**Comment by CDR-API-Stream** [comment]
> We do agree to using `404 Not Found` for the 3 cases provided (recommendation) and we want to draw Data Standards Body attention to one of the security principles followed by many APIs which is to return HTTP status code `404 Not Found` if a client requests a resource that exists, but that they are not authorised to access to avoid leaking information about other customers data.
> 
> The reasoning behind that is: if you don't have permission on a record, you shouldn't be able to confirm if that record exists.

Hi @AElharouny thanks for these comments. The DSB agrees that security considerations need to be taken into account in the situations you describe. This is considered under Decision Proposal #120.

**Comment by anzbankau** [comment]
We are supportive of proposal Option 3 – _Adopt 404 (Not Found) for URI resources and resource identifiers that don’t exist and resource identifiers that cannot be disclosed._

**Comment by NationalAustraliaBank** [comment]
NAB supports the inclusion of HTTP response code 404 (Not Found) into the data standards as outlined in Option 3.

**Comment by ryderwj** [comment]
Option 3 is preferred

**Comment by CDR-API-Stream** [comment]
This consultation is now being closed. Feedback received will be considered and an initial position will be drafted and published in due course.
