### ISSUE TITLE
Decision Proposal 127 - CX Guidelines for Enhanced Error Handling

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#127]
Placeholder issue for the consultation on CX Guidelines for Enhanced Error Handling.

Specifically, this decision proposal is seeking to consider the consumer experience concerns related to error scenarios between participants and the relevant CX guidelines to design consistent user experiences that support consumers when errors are encountered. Aspects of this consultation include: 
* what guidelines are needed for the display and communication of errors to consumers so that errors are comprehensible and actionable, 
* what guidelines apply for notifications when errors are encountered during unattended calls or the impacted consumer is a joint account holder who has elected consent,
* accessibility requirements and guidelines, and
* consideration to vulnerable customers and hardship

This proposal is not yet ready for publication but any initial community commentary on how the proposal should be developed is welcome.

**Comment by CDR-CX-Stream** [comment]
The following is provided as an update on this issue:

On [August 18th 2020, the DSB ran a workshop for the error handling series](https://consumerdatastandards.gov.au/event/dsb-enhanced-error-handling-online-workshop-03-consumer-experience-2/) that focused on paint points, errors, and CX issues in broad terms. 

To facilitate this, the CX Working Group developed a [journey map outlining the end to end experience based on the current CDR state.](https://miro.com/app/board/o9J_knxw6Pc=/) Participants provided feedback on this artefact and identified a range of issues and opportunities for improvement.

The workshop outputs were synthesised and [a revised journey map](https://miro.com/app/board/o9J_khmXIzU=/) produced with a more comprehensive view of pain points, opportunities, and a summary of items likely to be considered for CX Guidelines.

CX Guidelines will be developed covering a range of these issues along with a general section on errors that refers to existing CX Standards and Guidelines that are relevant to various error scenarios.

Revamped, web-based CX Artefacts are being released iteratively, beginning in December 2020, which will reflect a range of the issues identified in the error handling series.

As these issues will be dealt with at the level of CX Guidelines, no decision proposal is planned. This issue will be left open for another week if the community wants to provide further comments, and will then be closed by December 18th.

**Comment by CDR-CX-Stream** [comment]
This issue is now being closed in line with the previous comment.
