### ISSUE TITLE
Noting Paper - Non Functional Requirements

### ISSUE THREAD

**Issue by DimitriSty** [ConsumerDataStandardsAustralia/standards#129]
Xero has some concerns regarding the Performance Requirements published in the Data Standards section available on GitHub. 

As a cloud-based online accounting software provider, timely access to transactional data is critical to the customer experience and is an ingrained customer expectation. Currently Xero makes the majority of customers’ daily transactional data available before 9am the following day.

Based on the published performance requirements, the volume of Xero customer transactions and a potential 4-8 hour processing window, this customer expectation could no longer be met. 

Xero has been experiencing performance issues with the UK’s Open Banking APIs and has been working with the OBIE and banks directly for months to ensure we're aligned on customer expectations and minimal performance standards. Xero would welcome a similar conversation with Data61.

Another area of concern is the potential for low-quality data contained in the CDR APIs. Xero’s experience in the UK was that almost all the major banks delivered (and in some cases continue to deliver) a large amount of duplicates, missing transactions and ambiguous data. These issues have persisted for over 18 months.
Since 2019, Xero has seen a material increase in bank-feed related support cases coming through to our customer service team. This is almost entirely related to issues with Open Banking APIs. Again, Xero would welcome the opportunity to discuss our experiences and our customers’ expectations with Data61 and the ACCC.

**Comment by CDR-API-Stream** [comment]
Hi @DimitriSty, thank you for this feedback.

This issue tracker is for proposals and issues raised by the DSB seeking comment.  This post would be more appropriate for the issue tracker on the [standards maintenance repository](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues).

If you raise this query there we will response.  In the meantime this issue will be closed.
