### ISSUE TITLE
CX Stream: Feedback for Consumer Experience ResearchPhase 3: Round 3

### ISSUE THREAD

**Issue by supunperera** [ConsumerDataStandardsAustralia/standards#130]
Hi, I've got couple of points to get clarified from reference [1].

1. On the report the under slide 11, the link to "View ‘Requester/JAH1’ prototype" does not work. Was it intentional?

2. On the "Approver/JAH2 experience" prototype, it doesn't display what JAH1 has opted for (always allow sharing, share once or don't share). If that should be the behavior;
 2.1 Will JAH2 would prompted that his/her selection does not match the JAH1, or
 2.2 If system does allow different selection, then again this account would not be available for CDR data sharing as JAH1 and JAH2 did not agree on the same selection. In other words both parties should agree to the same selection in order to share the joint account?

Reference:
1. [https://consumerdatastandards.gov.au/wp-content/uploads/2020/05/CX-Report-_-Phase-3-_-Round-3.pdf]

**Comment by CDR-API-Stream** [comment]
Thank you for this feedback @supunperera.

For reference it is preferred if feedback on this issue tracker is limited to the specific threads initiated by the DSB.  Ad hoc feedback is welcome on the [standards maintenance repository](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues).  The CX team are also monitoring that issue tracker and will provide responses there.
