### ISSUE TITLE
Noting Paper 143 - CDR conventions

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#143]
This item is provided to communicate and seek feedback on a noting paper related to CDR conventions.

The noting paper is attached below:
<add attachment here>

Feedback is now open on this noting paper. Feedback is planned to be closed on 28 February 2021.
[Noting Paper - CDR conventions.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/5620409/Noting.Paper.-.CDR.conventions.pdf)

**Comment by commbankoss** [comment]
Commonwealth Bank requests an extension to 28/02 to respond on this issue.

**Comment by NationalAustraliaBank** [comment]
NAB also requests for an extension until 28/02 to respond to this noting paper.

**Comment by CDR-API-Stream** [comment]
This thread is being extended until the 28th of February as requested by participants

**Comment by NationalAustraliaBank** [comment]
As per our comments on the issue #142,  we believe conventions cannot be used to retrospectively update the DH implementations. If there are inconsistencies observed in the DH implementations, we recommend the standards be updated to be more prescriptive in such cases. For a new participant in the eco-system, who is already tasked with understanding the Rules, Standards , Decision proposals and Knowledge articles, the introduction of conventions will be an additional overhead, hence we recommend adding more examples to the standards or adding the conventions to the standards itself.

**Comment by CDR-API-Stream** [comment]
Thank you for the feedback.  This is being accommodated in our process for the development and publication of conventions and guidelines
