### ISSUE TITLE
Decision Proposal 016 - Customer End Point Structure

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/standards#16]
This decision proposal outlines a recommendation for the URIs for customer information API end points.  This proposal overlaps significantly with the ACCC rules so it has been authored to align with the proposed rules framework as much as possible.

Feedback is now open for this proposal. Feedback is planned to be closed on the 5th October.
[Decision Proposal 016 -  Customer End Points.pdf](https://github.com/ConsumerDataStandardsAustralia/open-banking/files/2417207/Decision.Proposal.016.-.Customer.End.Points.pdf)

**Comment by da-banking** [comment]
We accept the recommendation without modification.

**Comment by bazzat** [comment]
There's not a whole lot to argue about here :-) The ABA Open Banking Technical WG is supportive of this DP, with the proviso that some members queried how Rules relating to authorisation granularity will be supported with a single endpoint.

**Comment by DeloittePE** [comment]
We think this specific endpoint requires more consideration.

We believe that Customer will be specific to each industry and that this Proposal should be considering more the endpoint /banking/customer.

We recognise the value of a common resource to act as an integration point across the different industry domains. We suggest this resource is not Customer but may be something more like Person, Company or Party.

**Comment by TKCOBA** [comment]
COBA broadly supports Data61’s approach.  However, as this would be a cross-industry API, it may be beneficial to consider setting a minimum scope, while recognising the ACCC’s role to delineate the classes of information specified in the final Open Banking Designation Instrument.

**Comment by NationalAustraliaBank** [comment]
NAB supports the concept of giving customers the ability to explicitly give consent to share their personal information, however bundling all their customer information in one resource could lead to a situation where a customer consents to share information that is irrevocable. 

For example, a customer resource may contain private contact details which once shared, could lead to unwanted marketing communication outside of the customer's pre-set contact preferences. 
To avoid this scenario we recommend deconstructing the customer data model into scopes which include customer information which is useful for most use cases that does not include all the customer's personal identifying information, and other scopes which contains less sensitive information. This also creates a manageable extensibility framework moving forwards.

-   `/common/customer/{customerId}/profile `      (returns the full customer object)
-  ` /common/customer/{customerId}/summary`  (returns a less sensitive customer object)

However, further consideration is required on this resource as we are defining a resource which is intended to be used across industries and across customer segments which spans everyday Australians and large corporate institutions alike. Which could lead to further normalisation as below:

-  `/common/individual/customer/{customerId}`
- `/common/organisation/customer/{customerId}`

Once the intended payloads for this resource are under review we will be able to refine our collective thinking.

**Comment by JamesMBligh** [comment]
Response to the feedback provided is as follows:

**Common vs Banking**
Arguably, all of the in scope data except for products is "customer" data.  The ACCC draft rule framework articulates the in scope data in this way.  Under the current proposals this end point would _only_ have the cross-industry information.  Banking specific customer data such as payees, direct debits, etc would all be created under banking.

**Multiple End Points**
The separation of customer information into a summary and then detailed form is worthy of consideration to protect customer data leakage.  For the initial implementation it depends on the complexity of the payloads, which are being developed.  I will review the draft payloads we are working on and suggest a final position accordingly.

If two levels of detail is included in the end points then, by implication, an additional authorisation scope would be required to control access to the detailed customer data.

-JB-

**Comment by JamesMBligh** [comment]
I have now closed consultation on this decision. A recommendation incorporating feedback will be made to the Chair in due course.

-JB-

**Comment by JamesMBligh** [comment]
The finalised decision for this topic has been endorsed. Please refer to the attached document.
[Decision 016 - Customer End Points.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/2467300/Decision.016.-.Customer.End.Points.pdf)

-JB-
