### ISSUE TITLE
Decision Proposal 165 - Brand aware metrics

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#165]
This decision proposal provides options for modifying the metrics endpoints in the standards to accommodate multiple data holder brands supported by a single entity.

The proposal for consultation is attached below:
[Decision Proposal 165 - Brand aware metrics.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/6138518/Decision.Proposal.165.-.Brand.aware.metrics.pdf)

Feedback is now open for this proposal. Feedback is planned to be closed on Friday 16th April 2021.

**Comment by ryderwj** [comment]
Supportive of the recommended Option 4 until such time as a clear use case for a brand level breakdown in metrics is identified.

**Comment by commbankoss** [comment]
Commonwealth Bank is supportive of Option 4 – Keep the metrics API as it is currently.

**Comment by WestpacOpenBanking** [comment]
Westpac is supportive of the Data Standards Body’s preference for Option 4. There appears to be limited value in a brand query parameter for Get Metrics given the conventions proposed in [Noting Paper 169](https://github.com/ConsumerDataStandardsAustralia/standards/issues/169) which would require metrics to be provided for each ‘major’ brand via a different base URI

**Comment by EnergyAustraliaCDR** [comment]
EA supports option 4 recommended by DSB and others, which retain the status quo and requires no change until the benefits and use cases of other options are clearly defined.

**Comment by AElharouny** [comment]
On behalf of AGL Energy CDR technical working group

We are supporting of option 4 to leave the current metrics as is and not introduce brand awareness in metrics. Although it's important for us to have support for multiple brands in CDR; it's not clear at this stage the use cases where that would be useful to metrics API.

**Comment by NationalAustraliaBank** [comment]
NAB is supportive of current recommendation by DSB i.e. “Option 4 – Keep the metrics API as it is currently”.

**Comment by anzbankau** [comment]
ANZ is supportive of "Option 4 – Keep the metrics API as it is currently"

**Comment by CDR-API-Stream** [comment]
Based on the feedback received the DSB will not be recommending a change to the Chair in response to this proposal.  If circumstances change in the future we will revisit this concept via an additional consultation.
