### ISSUE TITLE
Noting Paper - White Label Conventions

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#169]
There have been an increasing number of questions recently regarding white label arrangements and how these should be implemented in a manner compliant with the standards.

To address this need for implementation certainty the DSB has created the attached noting paper:
[Noting Paper - White Label Conventions.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/6074220/Noting.Paper.-.White.Label.Conventions.pdf)

This noting paper is a set of conventions to guide implementors.  Once feedback has been obtained and responded to this content will be converted to conventions on the CDR Support Portal.  A workshop to address scenarios not covered by the conventions will also be scheduled for early April.

Feedback is now open on this noting paper. Feedback is planned to be closed on the 2nd April so that the feedback can be incorporated into the workshop.

**Comment by commbankoss** [comment]
Commonwealth Bank is of the view that conventions should not be introduced to the CDR ecosystem through noting papers as it introduces additional complexity and friction. New and existing participants must already work through several sources of information in order to fully understand their requirements and the context behind the evolution of the Standards. Rather, these items should be consolidated into the Standards through the existing Standards consultation process so that there are fewer sources from which to seek clarity. Deviating from established processes presents the possible future risk that conventions will be adopted as de facto Standards, without having passed through the established Standards consultation process.

Additionally, where appropriate relevant guidance on ZenDesk should be consolidated into the Standards to further reduce the need for extra sources.

**Comment by WestpacOpenBanking** [comment]
Noting that Westpac is currently working to align to the recommendations for secondary master brands with distinct domains for Public APIs and Get Metrics, we support the [updated Noting Paper](https://cdr-support.zendesk.com/hc/en-us/articles/900003938166-White-Labelled-brands-in-the-CDR) presented during the CDR Implementation Call and uploaded to the CDR Support Portal on 29 March 2021 (White Label Convention). It is plausible a non-designated brand owner (or even a designated data holder) will distribute several white label financial products from different designated data holders. These financial products may or may not be provided to the consumer in a single digital channel but might require separate CDR implementations from each data holder. We support the flexibility illustrated in the updated White Label Convention, which caters for a single designated data holder implementation per brand channel OR separate and multiple CDR implementations where a brand owner uses a single digital channel to distribute multiple white label financial products from different data holders.

**Comment by CDR-API-Stream** [comment]
Thank you to everyone who's put forward feedback. Consultation has been closed and feedback will now be reviewed and considered.

**Comment by CDR-API-Stream** [comment]
In response to the feedback from @SelenaLiuEA:

> As an overarching principle, it is important that the standards provide for flexibility so that the brand owner has a choice as to whether it registers the white label product under its own brand or as a separate brand. This should be a matter which the brand owner and white labeler can freely agree to.

The DSB is in agreement with this principle and this also aligns with the guidance provided by the rules team.  The guidance provided in this noting paper, and the underlying standards themselves, were specifically designed to maximise the optionality available to data holders in developing their commercial offerings while ensuring a good consumer experience and minimising implementation costs for ADRs.

> **1. Scenario 5: Where there is no single consumer identity for both the energy and white labelled NBN product** – the DSB proposes two options. We would support flexibility for Energy Co (brand owner) and Telco X (white labeler) to commercially agree to either Option 1 or 2. If this is not possible, we would support Option 2 only. Again, it might make sense that Telco X take on the data holder responsibilities separately for the NBN data. 

The presentation of the two options for scenario 5 was not intended to indicate that all participants would have to align to one option or another.  It is guidance that there are two valid ways of dealing with this scenario and the choice between these options is open to the brand owner and white label provider in their specific context.  We believe this aligns with the feedback that flexibility is needed.

> **2. Scenario 4: Where there is a single consumer identity** – we suggest there should be flexibility. The brand owner should be able to choose to register the white label brand under the same brand (Energy Co’s brand), or alternatively, choose to adopt Scenario 5 (and its options) and have two separate brands registered. The brand owner and white labeler should be able to commercially agree to either option. 

As per the comment above on scenario 5 the intention of providing this as guidance rather than as a proposal to change or extend the standards was to allow flexibility to participants to address their specific context.

> We also note that under Scenario 4, it seems the brand owner will have to provide the generic product data for the white labelled product (e.g. Energy Co would have to provide generic product data for Telco X’s white label NBN product). This would seem at odds with the CDR in the energy sector where the brand owner (Energy Co) does not have to provide generic product data for their own sector (e.g. electricity plans) but would have to provide it for the telecommunications sector. 

This feedback is noted and will be considered as we progress with the standards in the energy sector.  The current guidance is to inform the near term implementation obligations for the banking sector where this nuance has not needed to be addressed.

**Comment by CDR-API-Stream** [comment]
In response to feedback from @commbankoss:

> Commonwealth Bank is of the view that conventions should not be introduced to the CDR ecosystem through noting papers as it introduces additional complexity and friction. New and existing participants must already work through several sources of information in order to fully understand their requirements and the context behind the evolution of the Standards. Rather, these items should be consolidated into the Standards through the existing Standards consultation process so that there are fewer sources from which to seek clarity. Deviating from established processes presents the possible future risk that conventions will be adopted as de facto Standards, without having passed through the established Standards consultation process.

This noting paper does not propose to create any Data Conventions but instead outline supporting guidance regarding the white labelling arrangements previously articulated by the ACCC and the community and how they can be reflected in implementation in accordance to the data standards. As no feedback indicated the need for data standards changes to accomodate white labelling, changes to the Consumer Data Standards are not currently envisaged.

> Additionally, where appropriate relevant guidance on ZenDesk should be consolidated into the Standards to further reduce the need for extra sources.

This is opposite to the feedback previously provided by the community. Where data conventions become universally adopted and agreement with community results in a binding standard being created this would be reasonable. However as previously consulted on, data conventions are intended to be analogous to CX Guidelines to provide technical guidance without binding standards and these would not be part of the Consumer Data Standards for this reason.

**Comment by CDR-API-Stream** [comment]
In response to feedback from @WestpacOpenBanking:

> Noting that Westpac is currently working to align to the recommendations for secondary master brands with distinct domains for Public APIs and Get Metrics, we support the updated Noting Paper presented during the CDR Implementation Call and uploaded to the CDR Support Portal on 29 March 2021 (White Label Convention). It is plausible a non-designated brand owner (or even a designated data holder) will distribute several white label financial products from different designated data holders. These financial products may or may not be provided to the consumer in a single digital channel but might require separate CDR implementations from each data holder. We support the flexibility illustrated in the updated White Label Convention, which caters for a single designated data holder implementation per brand channel OR separate and multiple CDR implementations where a brand owner uses a single digital channel to distribute multiple white label financial products from different data holders.

Thank you for the feedback. This is aligned to the flexibility intended under the guidance provided.

**Comment by CDR-API-Stream** [comment]
Based on feedback no changes to the Consumer Data Standards have been identified to accomodate the scenarios presented. Further, the DSB received no feedback on alternative white labelling models that were not satisfied by the scenarios presented.

This consultation will now be closed and marked as `No Decision Taken` to reflect that no changes to the standards will be recommended to the Data Standards Chair.
