### ISSUE TITLE
Decision Proposal 017 - Product Reference End Point Structure

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/standards#17]
This decision proposal outlines a recommendation for the URIs for public product API end points.  This proposal overlaps significantly with the ACCC rules so it has been authored to align with the proposed rules framework as much as possible.

Feedback is now open for this proposal. Feedback is planned to be closed on the 5th October.
[Decision Proposal 017 -  Product Reference End Points.pdf](https://github.com/ConsumerDataStandardsAustralia/open-banking/files/2417211/Decision.Proposal.017.-.Product.Reference.End.Points.pdf)

**Comment by DeloittePE** [comment]
Deloitte concurs with the recommendation.

**Comment by bazzat** [comment]
The ABA Open Banking Technical WG supports the recommendation. Members note however that the devil, operationally speaking, will lie in the details - i.e. the payloads.

**Comment by TKCOBA** [comment]
COBA supports Data61’s approach.

**Comment by NationalAustraliaBank** [comment]
NAB supports this proposal.

**Comment by JamesMBligh** [comment]
To clarify, these end points are all scoped as Public and therefore unrelated to customer specific products.  All of these end points would only be expected to surface currently available products. 
 Information on customer products that have been originated (ie accounts) will be access via the /accounts/* end points.

It is agreed that the devil will be in the detail :)

-JB-

**Comment by JamesMBligh** [comment]
I have now closed consultation on this decision. A recommendation incorporating feedback will be made to the Chair in due course.

-JB-

**Comment by JamesMBligh** [comment]
The finalised decision for this topic has been endorsed. Please refer to the attached document.
[Decision 017 - Product Reference End Points.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/2467301/Decision.017.-.Product.Reference.End.Points.pdf)

-JB-
