### ISSUE TITLE
Special characters around  “effective” in cds_full

### ISSUE THREAD

**Issue by plambrechtsen** [ConsumerDataStandardsAustralia/standards#181]
The current cds_full has the open and close double quotes around “effective” in the specification and that is not properly converted in UTF-8 when viewing the YAML file.

This can be seen in the following files:

https://github.com/ConsumerDataStandardsAustralia/standards/blob/master/swagger-gen/api/cds_full.json#L368
https://github.com/ConsumerDataStandardsAustralia/standards/blob/master/docs/includes/swagger/cds_full.json#L481
https://github.com/ConsumerDataStandardsAustralia/standards/blob/master/docs/includes/swagger/cds_full.yaml#L445

`
data holder will use the “effective” date/time which will be defined as
`

When the YAML file is viewed via a browser in the main site:

https://consumerdatastandardsaustralia.github.io/standards/includes/swagger/cds_full.yaml

It is displayed as:

`
data holder will use the â€œeffectiveâ€ date/time which will be defined as
`

Whereas it should have a standard single quote character for the input string, or no quotes around effective at all then there wouldn't be the UTF-8 conversion issue.

**Comment by CDR-API-Stream** [comment]
Thanks @plambrechtsen.  Could you please raise this on the [standards-staging](https://github.com/ConsumerDataStandardsAustralia/standards-staging) repository.  This is where the mechanics of the authoring and publishing of the standards is consulted on.  This tracker is reserved for consultation on the standards themselves.

**Comment by plambrechtsen** [comment]
Thanks, raised as: https://github.com/ConsumerDataStandardsAustralia/standards-staging/issues/32
