### ISSUE TITLE
Noting Paper - ACCC Conformance Testing - Single industry solution for the CTS!

### ISSUE THREAD

**Issue by AMBL-CDR** [ConsumerDataStandardsAustralia/standards#184]
Dear ACCC and CDR,

As discussed at the Treasury Meeting today (18/5/2021) I feel there is growing industry momentum to have a common Conformance Test Suite (CTS) for smaller ADIs.

As such, please consider a single test / approval process for CTS for mutual ADI’s who would use a common banking system, and of course a common version.

Having a single sign-off/  approval mechanism and process for CTS will save time for ADIs, and it will also save us enormous costs.

Cost is a major factor for smaller ADIs given all the other compliance items (as mentioned by Luke Lawler – COBA) that are in progress.

If this service is to provide banking competition, the regulators and respective authorities need to be aware that added costs may in fact force further small bank mergers, which ultimately lessens competition.

Sincerely
Mal Webster
For Australian Mutual Bank

**Comment by CDR-API-Stream** [comment]
Hi @AMBL-CDR thanks for the feedback, unfortunately this is not the right repository to add commentary of this nature. We have moved this to Maintenance Issue 383: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/383.

We are aware there is no direct means to add commentary of this type and hope to publish a consultation exploring the tooling required by the Community. We would invite your input and insight into that consultation when published.
