### ISSUE TITLE
Decision Proposal 187 - CX Standards | Disclosure Consents

### ISSUE THREAD

**Issue by CDR-CX-Stream** [ConsumerDataStandardsAustralia/standards#187]
**June 29: Decision Made**
This decision was approved on 29 June 2021. The decision record is attached below:
[Decision 187 - Disclosure Consents.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/6730663/Decision.187.-.Disclosure.Consents.pdf)

Disclosure of CDR data to an accredited person under an AP Disclosure consent is now a permitted use or disclosure as per Rule 7.5A and Item 61 in the v2 Rules Explanatory Statement:

> **7.5A Limitation to disclosures of CDR data under a disclosure consent**
> Despite paragraph 7.5(1)(ca), disclosure of CDR data to an accredited person under an AP disclosure consent is not a _permitted use or disclosure_ until the earlier of the following:
> (a) 1 July 2021;
> (b) the day the Data Standards Chair makes the data standard about the matter referred to in subparagraph 8.11(1)(c)(iii).

> **_Item 61: new rule 7.5A_**
> The rule provides that a disclosure of CDR data to an accredited person under a disclosure consent is not a permitted use or disclosure until the earlier of 1 July 2021 or the day the Data Standards Chair makes consumer experience data standards for disclosure of CDR data accredited persons (which is referred to in a new paragraph inserted into subrule 8.11(1) by item 68).

---

**May 21: Decision Proposal Published**
This decision proposal relates to disclosure consents.

The v2 rules authorise consumer experience (CX) standards to be made for ADR disclosures to accredited persons (AP disclosures), which will be supported from 1 July 2021. 

The [recent Treasury announcement](https://treasury.gov.au/media-release/developments-australias-consumer-data-right-response-community-feedback) also notes the development of draft rules for consultation that will support other disclosure consent types, such as disclosures to trusted advisors (TA disclosure) and the disclosure of insights to non-accredited persons (insight disclosure).

This decision proposal seeks to consult on standards that are intended to be extensible and able to apply flexibly to an array of disclosure consents, including AP disclosures, TA disclosures, and insight disclosures. Amendments to extend the standards may be proposed following the publication of draft rules for TA disclosures and insight disclosures.

Specifically, this consultation seeks to determine:

1. Descriptions of data to be disclosed from an ADR
2. Descriptions of data to be collected and disclosed
3. Withdrawal standards for disclosure consents

The relevant decision proposal is attached below:
[Decision Proposal 187 - Disclosure Consents.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/6520548/Decision.Proposal.187.-.Disclosure.Consents.pdf)

**Feedback is now open for this proposal and will close on ~~Friday 18th~~ Thursday 24th June 2021.**

Edit: Consultation extended to 24.05.21 following community requests.
Edit: Decision made

**Comment by damircuca** [comment]
Hey People

Just had a read of the proposal doc along with the wireframe - this is awesome! 

One thing that did strike me was this daisy chaining concept of one ADR consenting to another, and so on. This really caught me off-guard as I can see potential issues in this daisy-chaining - in that all you need is the consumer to stop sharing in one app to impact all the others. 

My general concern with this is that we should try and avoid (as much as possible) from enabling a consumer to break an app (unknowingly) i.e. can we try and implement / design this in a way to not enable the consumer to make a mistake. 

I think what is needed is a class of institutions that can / cannot do this i.e. ADR sharing with other ADR should be avoided - instead we should limit this to the following models:

DH -> ADR -> Consumer
DH -> Intermediary -> ADR -> Consumer
DH -> Intermediary -> Consumer

We should not allow ADR to ADR, as it introduces daisy chaining which can get really messy. In saying this, it will create an issue when it comes to derived data, as one ADR will not be able to share their derived data with another ADR as it would be classified as CDR data? 🤷‍♂️

Apart from the above, Love the principle based approach in general.

**Comment by joshuanicholson** [comment]
Could we clarify if this proposal is also to cater for ADR's in a CAP collection arrangement? Based on the premise that a provider ADR under a CAP has no relationship with the consumer. 

This proposal is ADR2 requesting consent for data from ADR1 who already has consent to collect. In contrast under a CAP there would be a single workflow disclosing all parties but ultimately the principle ADR (ADR2) gains consent from the consumer to collect the data, via ADR1. 

for reference Ivan Hosgood had a good description of this in ZenDesk
https://cdr-support.zendesk.com/hc/en-us/articles/900003114503-Collection-Arrangement

**Comment by CDR-CX-Stream** [comment]
Thanks @damircuca and @joshuanicholson for your comments.

@damircuca the v2 rules made on 23 December allow ADR to ADR consents to occur from 1 July 2021 (see 'AP disclosure consent' in rule 1.10A(1)(c)), but we have passed this feedback onto the relevant team.

@joshuanicholson this proposal only refers to ADR to ADR transfers where the ADRs rely on the 'disclosure consent' provisions in rule 1.10A(1)(c). This proposal does not inherently apply to transfers between providers and principals as outlined in rule 1.10's CDR outsourcing arrangement.

**Comment by commbankoss** [comment]
Commonwealth Bank requests an additional week to consult on this proposal.

**Comment by CDR-CX-Stream** [comment]
In response to community requests this consultation will be extended for a week from today, until Thursday 24th June. Further extensions may not be considered so we encourage comments and particularly clarification requests as early as possible.

**Comment by SelenaLiuEA** [comment]
Hi All, 

Some minor questions from EnergyAustralia: 

1. These CX standards cover very limited requirements, can I confirm that all the other requirements relating to AP disclosure under the Rules apply in addition to these CX standards. 

2. Is this the only CX standard being made for disclosure consents? 

3. The Paper states that - "As part of the disclosure consent withdrawal process, ADRs MUST advise the consumer to review, 
with the recipient that the data was disclosed to: 
- How their data will be handled; and 
- The consequences of withdrawing the disclosure consent." 

Does "How their data will be handled" refer to deletion or de-identification by the recipient that has collected the data? Perhaps this should be made clear. If no, what is the purpose of this information? 

Thank you

**Comment by CDR-CX-Stream** [comment]
Hi @SelenaLiuEA,

1. Yes that is correct, the CX Standards are proposed to apply _in addition_ to the rules on AP disclosures.

2. The decision paper notes that these standards are intended to apply to an array of disclosure consents, such as the insight and trusted advisor disclosures referred to in the [Treasury announcement](https://treasury.gov.au/media-release/developments-australias-consumer-data-right-response-community-feedback). However, the paper also notes that amendments to extend the standards may be proposed following the publication of draft rules for TA disclosures and insight disclosures - which may result in additional standards for disclosure consents.

3. The data handling statement may refer to a number of things. For example, the ADR receiving the disclosed data (ADR2) may have their own disclosure consents, use consents, direct marketing consents, etc. with that consumer. These operate independently such that withdrawing a disclosure consent with ADR1 will not automatically withdraw those other consents with ADR2. ADR1 is not (required to be) aware of any other consents the consumer may have with ADR2. ADR1 is also not (required to be) aware of how ADR2 will handle that consumer's redundant data (i.e., if the data will be deleted or de-identified). The exact phrasing is at the discretion of the ADR, but the intention is to illustrate examples in the CX Guidelines similar to those provided in the consultation wireframes (see: [Miro](https://miro.com/app/board/o9J_lFPcM8I=/?moveToWidget=3074457358568549244&cot=14) | [PDF](https://consumerdatastandards.gov.au/wp-content/uploads/2021/05/DPxx-Wireframes_2-Disclosure-consents_Withdrawal.pdf))

**Comment by commbankoss** [comment]
Commonwealth Bank (CBA) is grateful to the DSB for extending the consultation period for this decision proposal. CBA proposes that the DSB host an industry workshop to discuss the use-cases and approach to enable “ADR to ADR” data sharing. As previously stated in our [October 2020 response to the Consultation on proposed changes to the Consumer Data Right Rules](https://www.accc.gov.au/system/files/Commonwealth%20Bank%20%2829%20October%202020%29.pdf), CBA remains concerned about the potential security and privacy risks associated with “ADR to ADR” data sharing, and that the current approach will not effectively deliver the desired consumer outcomes.

In addition, CBA recommends the following amendments to the Decision Proposal are required to ensure consumers can maintain control over their data and visibility with whom it is shared:

1. Duration of Sharing, Collection, and Use Consents should aligned to the way in which data sharing between Data Holders and ADRs is displayed and adjustable;
2. In a situation where an ADR shares customer data with a second ADR, the duration of Sharing, Collection, and Use Consents should be limited to the maximum sharing duration of the first ADR’s own Consent to Use. For example, if ADR1 has consumer consent to use data from a Data Holder until 1 November 2021,  then the Consent between ADR1 and ADR2 should not endure further than that date (1 November 2021). 
3. Data lineage and origins should be maintained throughout the data sharing chain. This will ensure that consumers are fully informed about which Data Holder the data originated from; which ADRs have shared it; and ultimately how their data is used.

**Comment by CDR-CX-Stream** [comment]
Thanks @commbankoss for this input.

In response to your numbered points:

1. As specified in rule 4.11(1A), 'ADR2' is required to have a consumer's consent to collect and use before 'ADR1' asks that consumer to give a disclosure consent. Disclosure consents only relate to the disclosure of specific data, not the uses to which ADR2 will put that data. This is analogous to DHs not having oversight of ADR use consents when asking a consumer to authorise the disclosure of the requested data. On these specific topics the requirements appear to be aligned with the current model for consents/authorisations with ADRs and DHs, respectively. We welcome further views on this point on this point, including corrections if we have misinterpreted the issue.

2. The rules determine the permitted consent durations that 'ADR2' can request, which may exceed the duration of the consent/authorisation that the consumer has with 'ADR1' and the respective DH. Rule 4.14(1B) states that ADR2's collection consent and ADR1's disclosure consent are bound, i.e. if one expires the other one also expires. However the separate consent provisions in the rules mean that ADR2 could continue to have an ongoing use consent, and may have established additional separate consents with that consumer. Further, ADR2 may be requesting data that relates to multiple DHs (and/or ADRs) with whom the consumer has multiple use consents with different durations. Finally, the standards cannot supersede the rules and as such the standards cannot require 'ADR2' to constrain consent durations as proposed.

3. Aspects of this proposal were considered but privacy issues were raised relating to the disclosure of a consumer's personal information - e.g. who they bank with. A more conservative approach was taken to support traceability by relaying this information to the consumer on 'ADR1's disclosure consent request and ADR1's dashboard, noting that this information would not be disclosed to 'ADR2'. We are however interested in further views on how this proposal could work.

In response to your starting query, the v2 rules allow AP Disclosures to occur from 1 July 2021 in accordance with CX Standards. Standards development will need to be progressed accordingly but we welcome further input in how they might evolve. On the topic of ADR to ADR data sharing in general, we acknowledge these concerns and welcome the raising of any specific issues and topics that CBA would like to see explored so the DSB can consider these items and the possibility of future workshops.

**Comment by CDR-CX-Stream** [comment]
Thanks to all who provided feedback. Feedback on this decision proposal is now closed. Submissions have been reviewed and the decision proposal is now being finalised.

**Comment by CDR-API-Stream** [comment]
The changes to be included in v1.11.0 have been staged here: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.11.0...dp/187

These changes remain subject to the Data Standards Chair's approval.

**Comment by CDR-CX-Stream** [comment]
This decision was approved on 29 June 2021. The decision record can be found in the original post.

As outlined in the original post, disclosure of CDR data to an accredited person under an AP Disclosure consent is now a permitted use or disclosure as per Rule 7.5A and Item 61 in the v2 Rules Explanatory Statement.

Standards changes arising from this decision will be incorporated into the v1.11.0 release.

**Comment by CDR-CX-Stream** [comment]
This decision has been reflected in the [v1.11.0 release of the CX Standards](https://consumerdatastandardsaustralia.github.io/standards/#consumer-experience). The issue will now be closed.
