### ISSUE TITLE
Decision Proposal <Number> - <Title>

### ISSUE THREAD

**Issue by PaulaAF11** [ConsumerDataStandardsAustralia/standards#188]
**Note that issues should only be raised in this repo by the Lead of the CDS API Stream or delegate**
This decision proposal outlines a recommendation for <describe decision topic>.

The consultation draft for this decision proposal is attached below:
<add attachment here>

Feedback is now open for this proposal. Feedback is planned to be closed on <enter feedback close date>.

**Comment by CDR-API-Stream** [comment]
This issue is closed. Community members wishing to raise change requests may do so on [Standards Maintenance](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/).
