### ISSUE TITLE
Decision Proposal 196 - Candidate DER End Points

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#196]
This decision proposal contains a recommendation for the candidate URIs and end points for Distributed Energy Resources (DER) Data.  This proposal has been developed with the aid of AEMO.

The decision proposal is embedded below:
[Decision Proposal 196 - Candidate DER End Points.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/7073285/Decision.Proposal.196.-.Candidate.DER.End.Points.pdf)

This consultation will be open for feedback until the 1st October 2021.

**Comment by EnergyAustraliaBA** [comment]
Hi - we note that NMI is not included in the response. Retailer will request DER data on NMI level. Is there any reasoning of not providing NMI back to requestor?

**Comment by johnAEMO** [comment]
Thank you for the opportunity to respond to the above Decision Proposal.

AEMO's response is in the attached document:
[Decision Proposal 196 - AEMO Response v1.0.docx](https://github.com/ConsumerDataStandardsAustralia/standards/files/7264858/Decision.Proposal.196.-.AEMO.Response.v1.0.docx)

**Comment by CDR-API-Stream** [comment]
Thanks everyone for the feedback.  This consultation is now being closed.  We will provide a response to feedback shortly.

**Comment by CDR-API-Stream** [comment]
Please find attached the final decision of the Chair:
[Decision 196 - Candidate DER End Points.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/7394070/Decision.196.-.Candidate.DER.End.Points.pdf)
