### ISSUE TITLE
Decision Proposal 197 - Candidate Account End Points

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#197]
This decision proposal contains a recommendation for the candidate URIs and end points for energy accounts.

The decision proposal is embedded below:
[Decision Proposal 197 - Candidate Account End Points.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/7200734/Decision.Proposal.197.-.Candidate.Account.End.Points.pdf)

Note that this proposal has incorporated changes arising from the generic tariff consultation (for the tailored structure).  It also incorporates initial feedback from AEC members on incorporate C&I customers.

This consultation will be open for feedback until the 22nd October 2021.

**Comment by EnergyAustraliaBA** [comment]
FYI - attaching a pack that was provided by EA to the Data Standards Advisory Committee (DSAC) re C&I customers and CDR.  Has relevance for DPs 197 and 198
[DSAC - EnergyAustralia presentation 8 Sep 2021.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/7308740/DSAC.-.EnergyAustralia.presentation.8.Sep.2021.pdf)
.

**Comment by EnergyAustraliaBA** [comment]
Please find below - and in the two attached documents - EnergyAustralia’s response to Decision Proposal 197 (Account End Points, which include tailored tariff data).
Note that this feedback reflects our initial assessment from a business perspective, and is provided prior to commencing detailed assessments and overall ‘solutioning’.
The two attached pdfs are: 1. Overall and field by field feedback for both the Mass Market and C&I customer segments, and; 2. a Data Set summary providing our initial assessment of each dataset from a C&I perspective.

**Some of the key items included in our detailed feedback are:**

**Overall**
- After careful analysis and consideration with our Mass Market and C&I SMEs,  EA believes it is not compatible to have both Mass Market and C&I data payloads on a single API endpoint - see attached documents for further detailed information. Therefore EA recommends that DSB separates the Mass Market and C&I Data payloads into two separate API Endpoints.

**Mass Market segment**
- See overall comments on Page 2 of the attached MM and C&I feedback document
- Concessions data:  not all concessions fit the attributes described

**C&I segment**
- We believe many data sets are “not serviceable” (meaningful data cannot be provided) or are “partly serviceable” (data can be provided but may not meet CDR expectation and context). Some key examples of this are:
o	“Plans” as such don’t exist for C&I like they do for mass market (where there is a plan that is widely marketed under a particular name). In contrast C&I products are highly bespoke/negotiated with the customer. As such we are unable to meaningfully populate this data.
o	“Detailed Account Data” section - Charges generally and additional “pass-through” data
o	Pricing and Discounts don’t cover C&I customers as additional types of pricing are used in C&I and pricing is not discounted in the same way as mass market plans (i.e. prices are just set lower) 

[EA Decision.Proposal.197.-.Candidate.Account.End.Points_MM and CI feedback.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/7393606/EA.Decision.Proposal.197.-.Candidate.Account.End.Points_MM.and.CI.feedback.pdf)
[EA Decision Proposal 197_Dataset Summary_C&I perspective.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/7393610/EA.Decision.Proposal.197_Dataset.Summary_C.I.perspective.pdf)

**Comment by PratibhaOrigin** [comment]
As raised with the Commonwealth Treasury and DSB, we remain concerned with the proposed inclusion of large Commercial and Industrial (C&I) energy consumers within the CDR framework. C&I businesses enter into energy pricing arrangements that are markedly different from “traditional” retail pricing structures commonly used for (small) mass market consumers.  C&I consumers largely rely on unbundled rates, the direct pass through of costs (ie determined at the time of billing), have separate contracts for different services (ie metering, network connection) or could have rates that span over a number of sites.  A challenge for CDR is how to adequately capture these differences at an efficient cost and whether brokers (who largely request data on a C&I’s behalf) is able to directly utilizes the services of CDR. 

For this Account End Point API (current tariff details), we understand that the intent of this API is to provide the consumer with a view of their rates that they can expect to see on their statement as opposed to a copy of their energy contract.  For C&I consumers, this may only be a proportion of the total charges relevant to the consumer as some rates are dependent on other market participants (ie network, AEMO, metering provider). 
At a high level, the following changes have been proposed for C&I consumers if a decision is made to include them and the scope is only limited to the Invoicing, Billing & Account payloads. If there is a decision made by Rules team on the inclusion of C&I consumers, we would like to review all other APIs, including the common APIs from a C&I perspective. 

**Account Detail Payload** 
•	The transaction type or charge type categories across all 3 APIs will need to be expanded to cater to the various unbundled categories represented on an Invoice. The proposed list of categories is “usage”, “generation”, “onceOffCharge”, “onceOffDiscount”, “environmentalCharge”, “regulatedCharge”, “networkCharge”, “meteringCharge”, “retailServiceCharge”, “RCTICharge”, and “otherCharge”
•	Contract level accounts with no linked consumers will be left out of scope as these accounts only hold contract details and are not used for billing
•	"demandCharges", "controlledLoad" and "dailySupplyCharges" blocks within the Account Detail API are not going to be applicable for C&I customers as these will be passed through from the network and we will display these (if applicable) under the "networkCharges" category
•	The format for all applicable rates (time of use, metering, environmental, regulated etc.) should include the rate, unit of measure, start date and end date
•	The enumeration list against "fee term" should also include a VARIABLE option to cater to fees where the term is not fixed. For example, if a customer terminates their contract before the agreed end date, they may be charged a variable fee that is calculated using different elements or factors
•	Rename "tariff" to "usageCharge" as the block only refers to usage or energy charges
•	"pricingModel" and "timezone" to be moved to the "usageCharge" category as these fields relate to energy charges only
•	In case we are not able to provide all the data for a given account for any reason – could be that the pricing is highly bespoke or a new product has been introduced with charges and features not supported by the current payload structure – how are these expected to be handled? Would a new field be available for us to populate why we cannot provide the data?
•	It is understood that C&I consumers would be required to individually request data on an account-by-account basis.  That is, if a customer has 10 accounts with a retailer, they need to provide consent for each and every account. 
•	Pg-4 refers - Concession & Hardship Data . However, our understanding based on the draft rules is that ‘hardship’ details are now kept out of scope of CDR . Reference – Rule 1.3 of Schedule 4 of the Rules. Can DSB confirm the same ?

**Concession Data**
•	For C&I customers, concessions would be applicable if there are any eligible persons residing at the property for a given bill period. So, this is dependent on the number of people at the property and not related to the end customer (for e.g., caravan parks). Therefore, we will not be able to provide the data in the requested format which is tailored to mass market and propose that C&I customers be left out of scope for this API

Further feedback (at a field level) has been provided in the attached document. For a detailed list of fields proposed to be modified, added, and removed, please refer the attachment.
[DP 197 Account API ORIGIN - October 2021.docx](https://github.com/ConsumerDataStandardsAustralia/standards/files/7394164/DP.197.Account.API.ORIGIN.-.October.2021.docx)
