### ISSUE TITLE
Decision Proposal 198 - Candidate Billing & Invoicing End Points

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#198]
This decision proposal contains a recommendation for the candidate URIs and end points for Billing and Invoicing data.

The decision proposal is embedded below:
[Decision Proposal 198 - Candidate Billing & Invoicing End Points.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/7200980/Decision.Proposal.198.-.Candidate.Billing.Invoicing.End.Points.pdf)

Note that this proposal has incorporated changes arising from initial feedback from AEC members on incorporate C&I customers.

This consultation will be open for feedback until the 22nd October 2021.

**Comment by jonmilne** [comment]
Some observations/suggestions for the Billing Transaction Common Types:

**usage:timeOfUseType**: I note the [previous consultation](https://github.com/ConsumerDataStandardsAustralia/standards/issues/149#issuecomment-792437049) where the inclusion of 'OFF_PEAK_DC' was requested and subsequently included by the DSB, but there does not appear to be any information about its meaning. 

Is this intended to represent a controlled load? If not, should 'CONTROLLED_LOAD' be added as an additional enum to identify controlled load usage, without ambiguity? 

**onceOff** object: I note the [previous consultation](https://github.com/ConsumerDataStandardsAustralia/standards/issues/116#issuecomment-722044442) where the DSB indicated that the 'onceOff' charge object could/should be used for non-usage charges including metering, demand and daily supply charges. However, there is only a free text description field to describe the charge. This presents issues for machine readability and makes it difficult for ADRs to interpret these charges, particularly if the same charges are described in different ways by data holders. 

Should an additional enumerator be included for this object, as a mandatory field, to create some consistency and to aid interpretation of the charges in this object? i.e. DAILY_SUPPLY, METERING, OTHER etc.

**General comments/questions regarding GST**:  Presumably, invoice amounts are intended to be returned inclusive of GST given this is how they would appear on a customer bill. However, with respect to charges in billing payloads, are these expected to be returned inclusive or exclusive of GST? I note there is an 'adjustments' object, is this intended to be used for this purpose if the usage charge itself is exclusive of GST? If so, the prior comments regarding machine readability of the description field apply. We recommend consideration be given to the application of GST in these payloads, with inclusion or exclusion made explicit.
