### ISSUE TITLE
020 Noting Paper - Information Security Working Group Operating Model

### ISSUE THREAD

**Issue by ellenbroad** [ConsumerDataStandardsAustralia/standards#20]
I'm delighted to introduce @camtepe, Senior Research Scientist with Data61 and information security expert, who will be leading the Information Security Working Group. @camtepe has prepared a proposed operating model for any feedback and will begin posting Decision Proposals from next week. 

The Working Group will follow a similar model to the API Standards Working Group, while anticipating that a secure closed environment may need to be set up for more sensitive discussions, as the topics progress. 

Feedback on the Operating Model and a potential forum for more sensitive discussions welcome. 

And welcome @camtepe ! 
[ISG-DSB-Operating Model.pdf](https://github.com/ConsumerDataStandardsAustralia/open-banking/files/2317171/ISG-DSB-Operating.Model.pdf)

**Comment by JamesMBligh** [comment]
Welcome @camtepe 

-JB-
