### ISSUE TITLE
Normative Standards Review (2021)

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#203]
This issue has been created to consult on the normative standards review outlined in the [DSB Future Plan](https://github.com/ConsumerDataStandardsAustralia/future-plan/issues/34). The purpose of this review process is to review and uplift the CDS where changes in upstream standards are identified. The CDS relies upon a number of external standards, and over time these standards can be revised and newer versions issued. To remain current, this review process seeks to consider the impact of any changes and the approach to align the CDS as required.

A high level overview of the standards under review can be found here:
https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/tree/master/reviews/2021-05

This issue is not a Decision Proposal. Rather it provides a mechanism for feedback to this initial analysis. Targeted Decision Proposals will be created after reviewing feedback of implementation impacts. There is currently no closing date currently planned for this analysis.

**Comment by CDR-API-Stream** [comment]
[FAPI Part 1 Analysis](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/blob/master/reviews/2021-05/analysis/analysis-fapi-part1-20210614.md) has been published. The DSB has not made any recommendations regarding transition phasing or adoption of each change. The DSB welcomes feedback from the community regarding these aspects and any other changes the community identify.

**Comment by CDR-API-Stream** [comment]
[FAPI Part 2 Analysis](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/blob/master/reviews/2021-05/analysis/analysis-fapi-part2-20210621.md) has been published. The DSB has not made any recommendations regarding transition phasing or adoption of each change. The DSB welcomes feedback from the community regarding these aspects and any other changes the community identify.

**Comment by CDR-API-Stream** [comment]
Please also note the OIDF has conducted an [analysis of FAPI ID2](https://bitbucket.org/openid/fapi/src/master/FAPI_1.0/changes-between-id2-and-final.md) (essentially what the CDS refers to as Draft 06) to FAPI 1.0.

**Comment by CDR-API-Stream** [comment]
[Requirements Levels analysis](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/blob/master/reviews/2021-05/analysis/analysis-rfc2119-rfc8174-20210519.md) has been published. Due to the simplicity of the overall change, the DSB has made recommendations regarding adoption of the change.s The DSB welcomes feedback from the community regarding these recommendations and any other changes the community identify. Further analysis of the changes to the CDS will be provided in due course.

**Comment by CDR-API-Stream** [comment]
Please not the issue description has been updated. This issue has been raised as a way to track review progress across all normative standards. It is not a Decision Proposal but instead presents the initial analysis. It is expected that targeted Decision Proposals will be created once feedback from the community on impacts to implementation are discussed.

**Comment by CDR-API-Stream** [comment]
[Pushed Authorization Requests (PAR) analysis](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/blob/master/reviews/2021-05/analysis/analysis-par-20210704.md) has been published for review and feedback. This analysis compares Draft 02 to Draft 09.

**Comment by spikejump** [comment]
In the [FAPI Part 2 Analysis](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/blob/master/reviews/2021-05/analysis/analysis-fapi-part2-20210621.md) above, we note the below:

> 5.2.3. (9): NEW No change unless using PAR, in which case the additional claims outside the request object aren't required. For backwards compatibility, it doesn't hurt if the client continues to send these to the authorisation endpoint.

It might be worthwhile to call out that when the standard is adopted by the CDS ecosystem and when PAR is being used, the Data Holder's Authorisation Server must not throw an error when ADRs do not send the additional claims (response_type and scope).  This is because there's discrepancy in existing Data Holders implementation where some throws an error and some don't.
