### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by seanke** [ConsumerDataStandardsAustralia/standards#226]
On this page:
``
https://consumerdatastandardsaustralia.github.io/standards/#certificate-management
``

These link are broken:

![image](https://user-images.githubusercontent.com/34672648/142962098-ec01524c-118e-4b44-8925-42765893cd44.png)

**Comment by CDR-API-Stream** [comment]
@seanke Thanks for highlighting this issue.

In the meantime, please feel free to refer to the [archived](https://consumerdatastandardsaustralia.github.io/register/#certificate-management) version of the CDR Register design as those links are working and contain the same information as those you have highlighted.

**Comment by CDR-API-Stream** [comment]
An issue on standards staging has been raised to ensure this gets fixed in the next release of the standards.  This issue will be closed in deference to that issue.
