### ISSUE TITLE
Noting Paper - Representatives and Affiliates Conventions

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#228]
This noting paper has been created to provide interim guidance on how the Register standards should be utilised to represent experiences for Affiliates and CDR Representatives.
[Noting Paper - Representatives and Affiliates Conventions.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/7688990/Noting.Paper.-.Representatives.and.Affiliates.Conventions.pdf)

**Note:**
- The guidance in this paper is predicated on how the existing implemented standards can be used
- The DSB believes that changes to the standards will be required to fully support this models but this will occur in subsequent consultations.  There is already good discussion on this topic occurring on [Standards Maintenance CR 427](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/427)
- This is a complicated topic so it is not assumed that we have been able to accommodate all possible business models and structures.  The guidance is therefore being posted here with the opportunity for feedback to be supplied so that models that have not been anticipated can be added
- Although feedback on additional business models may be incorporated the guidance should still be considered valid for the majority of situations

We will leave this thread open for feedback until 21st January so that the guidance can be finalised and posted on the Support Portal before 1st February.

**Comment by commbankoss** [comment]
CBA appreciates the opportunity to provide feedback on this Noting Paper.

Of the possible convention scenarios set out in this noting paper, CBA believes that implementing scenario 2 could help the ecosystem and participants address some of the issues raised in DP 225, as long as the customer is able to easily identify the party that is receiving the data via the Data Holder dashboard, and the ADR dashboard (for example by the naming of the software product in a way that makes it clear for a customer what use case it is related to and what entity has access to their data).  

More specifically, we believe this option will help address security and privacy concerns relating to: (1) distinct ID permanence IDs linked to the Affiliate/Representative; and (2) providing the ability to suspend a particular affiliate/representative (based on the software product) without having to suspend all affiliate/representatives associated with a given ADR.

**Comment by CDR-API-Stream** [comment]
Thanks to CBA for the feedback.  We will work to publish this guidance on the CDR portal and will emphasise the need for a customer to easily identify the party.

We will now close this feedback thread.
