### ISSUE TITLE
BUG in cds_banking.yaml/banking/products

### ISSUE THREAD

**Issue by tomred-net** [ConsumerDataStandardsAustralia/standards#232]
cds_banking.yaml:1392 /banking/products 
refers to $ref: '#/definitions/ResponseBankingProductList':1472 which does not exists in definition. 

This appears to have been replaced by $ref: '#/definitions/ResponseBankingProductListV2'. 

Line 1472 should be updated to refer to ResponseBankingProductListV2 instead of ResponseBankingProductList.

**Comment by tomred-net** [comment]
Seems like this should be in a repo separate to this one. Closing and moving to the other repo.

**Comment by CDR-API-Stream** [comment]
Thanks @tomred-net.  Good pickup though.  This should now be addressed in v1.16.0.

This issue will be closed.

**Comment by CDR-API-Stream** [comment]
For traceability, here is the link to the issue in standards-maintenance which has been addressed in v1.16.0
https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/454
