### ISSUE TITLE
Use of Open Data Principles

### ISSUE THREAD

**Issue by riannella** [ConsumerDataStandardsAustralia/standards#234]
Hi, Was wondering if the use of "open data principles" has been discussed by this group (and/or decisions made)?

Specifically was keen to see how all the "enumerated values" can be turned from "strings" to "things".
That is, use URIs to identify each, which are resolvable in a vocabulary service.

So, instead of (string) categories like "BUSINESS_LOANS" and "TERM_DEPOSITS", these are URIs.
(note, they still can be parsed as strings, but the URI will enable global uniqueness, compassion, and sameness - as well as the possibility to resolve them and return more metadata...eg SKOS)

As well, the move towards supporting JSON-LD is highly recommended to support identity, typing, lists...and mapping to semantic models.

Look forward to your responses...

Cheers - Renato

**Comment by CDR-API-Stream** [comment]
Thanks Renato.  The threads on this repository are used for statutory consultation on the standards.  Your query would be welcome on the companion [maintenance repository](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance) where we handle change requests and suggestions of this nature.

We would appreciate it if you could raise your query there.
