### ISSUE TITLE
Noting paper 024 - in person API standards get together Thursday 4 October, Melbourne

### ISSUE THREAD

**Issue by ellenbroad** [ConsumerDataStandardsAustralia/standards#24]
As James moves into the home stretch of decision proposals for the API standards working group, we are planning an in person informal session to discuss outstanding key issues and sound out things to think about moving forward. I know James already circulated a 'save the date' in his API Standards mailing list last week, and a link to RSVP will follow tomorrow, but I wanted to post the details here too in case some people contributing to the repository aren't on that mailing list.

The meeting will be:
2pm - 4pm (followed by light refreshments)
Thursday 4 October
Data61 Demo space, Level 1, 710 Collins Street, Docklands

For those of you who aren't on James' mailing list, you can register here: https://csiro.us18.list-manage.com/subscribe?u=fb3bcb1ec5662d9767ab3c414&id=a4414b3906

We're looking at adding video/teleconferencing facilities and will endeavour to do so if we can. We'll also prepare a read out of key discussions from that meeting so that the conversation can be continued online. This won't be the only in person opportunity to discuss the API specifications, we're conscious that the spread of participants in open banking makes choosing one geographical location hard! 

Watch this space for an RSVP link tomorrow following on from last week's save the date. It will also go out simultaneously to the API Standards mailing list and Advisory Committee. If you do happen to be based in Melbourne, please do come along.

**Comment by ellenbroad** [comment]
Hi everyone, link to RSVP is here: https://www.eventbrite.com.au/e/api-working-group-meeting-tickets-50585397285.

**Comment by darkedges** [comment]
How can you get onto the API standards mailing list?
