### ISSUE TITLE
Decision Proposal 245 - Enhancing Data Recipient Accreditation Negotiation

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#245]
This decision proposal outlines questions to help develop a recommendation for Enhancing Data Recipient Accreditation Negotiation

The decision proposal is embedded below:
[Decision Proposal 245 - Enhancing Data Recipient Accreditation Negotiation.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/8385685/Decision.Proposal.245.-.Enhancing.Data.Recipient.Accreditation.Negotiation.pdf)

~This consultation will be open for feedback until 01st May 2022 subject to the caretaker period.~

---

The consulation period for this DP has been extended to the 27th May 2022, the Friday after the caretaker period is expected to conclude.

**Comment by AusBanking** [comment]
The ABA makes the below submisison in relation to DP 245

[220527 - ABA Submission - DP 245.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/8783813/220527.-.ABA.Submission.-.DP.245.pdf)

**Comment by commbankoss** [comment]
Commonwealth Bank supports the ABA’s view on Decision Proposal 245,

**Comment by NationalAustraliaBank** [comment]
NAB supports ABA's view on this decision proposal

**Comment by WestpacOpenBanking** [comment]
Westpac supports ABA’s view on Decision Proposal 245.

**Comment by CDR-API-Stream** [comment]
Thanks to everyone who provided feedback. This conversation will now be locked while the submissions are considered.
