### ISSUE TITLE
Noting Paper 025 - Upcoming information security working group decision proposals 

### ISSUE THREAD

**Issue by camtepe** [ConsumerDataStandardsAustralia/standards#25]
Information Security Technical Working Group is currently preparing decision proposals covering FAPI aspects of: 

1-    Authorization flows including support for authentication code and implicit grants.

2-    Authentication models between customer - data holder and accredited receiver - data holder. 

3-    Transport security options including the use of TLS with certificates (MTLS). This decision relates to ACCC’s directory design, e.g., the existence of a certificate authority or a public key director.

4-    Message signing, non-repudiation, logging and auditing.

**Comment by mathiasfaureMac** [comment]
on point 3:
Can we avoid using transport level for security and just use layer 7? 
JOSE header could cover authentication and non-repudiation.
