### ISSUE TITLE
Decision Proposal 267 - CX Standards | Telco Data Language

### ISSUE THREAD

**Issue by CDR-CX-Stream** [ConsumerDataStandardsAustralia/standards#267]
**November 11: Decision Proposal 267 v2 Published**
Version 2 of decision proposal 267 relating to telco data language standards includes refined proposals based on consumer experience (CX) research, community feedback on the proposed standards and draft rules, and further internal analysis.

This decision proposal seeks to:
1. Determine appropriate changes to the CX data standards to accommodate the telecommunications sector
2. Determine the specific language standards to be used for the telecommunications sector

Version 2 of DP267 is attached below:
[Decision Proposal 267 v2](https://github.com/ConsumerDataStandardsAustralia/standards/files/9985007/DP267.Telco.data.language.v2.0.pdf)

**Feedback is now open for this proposal and will close on ~Friday 9 December 2022~ a date to be determined pending the making of the telco rules.**

This is intended to be the final consultation on the proposed telco data language standards. Subject to the making of the telco rules, community feedback, and technical standards changes, the Data Standards Body (DSB) will then propose to the Data Standards Chair that these be made into binding data standards. Any further changes will then be considered as part of [standards maintenance](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues).

---
**August 18: Decision Proposal 267 v1 Published**
This version 1 of decision proposal 267 relates to consumer experience (CX) standards for telco data language.

This consultation is intended to be conducted in two rounds. A subsequent consultation will be conducted to finalise the data language standards.

This paper seeks to define standards for the telco sector, which will only become binding in accordance with the making of the telco rules, and the making of standards by the Data Standards Chair. The proposals will be subject to change pending further changes and decisions based on rules and technical standards refinement.

The version 1 of decision proposal 267 covering telco data language standards is attached below:
[DP267 Telco data language.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/9371329/DP267.Telco.data.language.pdf)

The community is encouraged to view the existing [banking language standards](https://consumerdatastandardsaustralia.github.io/standards/#data-language-standards) and [energy language standards](https://consumerdatastandardsaustralia.github.io/standards/#energy-language) for reference.

~**Feedback is now open for this proposal and will close on Thursday 15 September 2022.**~

**N.B.** The consultation on v1 of DP267 was proposed to run until Thursday 15 September 2022. DSB left this issue open for comments while considering existing standards and rules feedback and developing version 2 of DP267.

---
Edit: Consultation extended pending the making of the telco rules
Edit: v2 of DP267 published
Edit: Note on consultation window updated
Edit: Placeholder updated; decision proposal published

**Comment by CDR-API-Stream** [comment]
[DP267 Telco data language.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/9371329/DP267.Telco.data.language.pdf)

**Comment by CDR-CX-Stream** [comment]
This is a reminder that we are now at the halfway point for the first round of DP267 consultation, which closes on **Thursday 15 September 2022**.

Further feedback can be provided on a final draft of the standards proposed in DP267 in the coming weeks.

The ability to incorporate late feedback with substantial changes will be constrained. We urge the community to engage as early as possible if there are significant concerns, issues, or alternative proposals.

A public workshop is planned during the second round of DP267 consultation to facilitate the last round of submissions before the telco language standards are finalised.

**Comment by CDR-CX-Stream** [comment]
As part of the DSB's ongoing analysis, the below changes are expected to be incorporated into v2 of DP267.

**Proposed change 1**
This change proposes that the 'Account number' permission be removed from the 'Billing payments and history' data cluster (telco:billing:read). This change will maintain consistency with the decision proposals related to billing ([DP264](https://github.com/ConsumerDataStandardsAustralia/standards/issues/264), [DP265](https://github.com/ConsumerDataStandardsAustralia/standards/issues/265), [DP266](https://github.com/ConsumerDataStandardsAustralia/standards/issues/266)) and the [equivalent energy data cluster](https://consumerdatastandardsaustralia.github.io/standards/#energy-language).

**Proposed change 2**
This proposes that 'Service and data usage' be entirely removed as a standalone data cluster, including the associated permissions ('Total number of calls and messages', 'Amount of data uploaded/downloaded', and 'Call, message and data usage details'). This change will maintain consistency with the the decision proposals related to billing ([DP264](https://github.com/ConsumerDataStandardsAustralia/standards/issues/264), [DP266](https://github.com/ConsumerDataStandardsAustralia/standards/issues/266)), which captures usage details as part of the billing scope.

Instead, v2 of DP267 will rely on the 'Usage for billing period' permission to inform consumers of the fact that their usage details will be shared. This permission can be found in the 'Billing payments and history' data cluster (telco:billing:read).

This DSB seeks feedback on these changes and particularly whether the use of 'Usage for billing period' is sufficient for the purposes of informed consent, or if extra detail on usage is warranted to make clear that this will share a summary of calls, messages, and data usage.

**Comment by Telstra-CDR** [comment]
This is Rish Kundavaram from Telstra. We acknowledge and accept the proposed changes 1; For proposal 2, we recommend additional detail to be added on usage to make clear that this will share summary of calls, messages and data usage. 

Telstra have reviewed the complete design proposal and here are some feedback points on the proposed CX Standards |Telco Data Language

**Individual Customer Data**
•	Clarity on mail Address – assume this is postal address. The language of “Postal” is more common among the telco customers.  

**Business Consumer Data**
•	Establishment Date – Establishment date of the Organisation OR establishment of account with the Data Holder. 
•	Charity Status currently not in common APIs. 

**Telco Accounts** 
•	The language of “Accounts and Services” instead of  “Accounts and Plans” perhaps is more appropriate. In our self-care mobile applications we refer to services first and subsequently customers can view the plan associated to each service.
•	Description of Authorized Contacts  defined as “means information that identifies or is about the operation of the account”  instead of “People you've given access to manage your accounts and services”
•	Product specific data perhaps can be referred to as Service Specific Data. Consider alternate language and refer to service specific data such as: 
o	Service specific data:
          	The type of service (such as pre-paid or post-paid, NBN or other network,
ADSL/VDSL)
         	The service identifier
         	The name of the plan
         	The plan details including pricing information
         	The retailer brand providing the service
         	Account specific data:
         	The account number
         	The account name
         	The account creation date

**Billing** 
•	Challenging the value of including Invoice numbers in Billing data clusters/payloads. Invoices can be many across multiple years. We will be following up on this when the billing payloads are open for feedback. 

Please don’t hesitate to involve us in any workshops to deep dive into the experience and language.

**Comment by CDR-CX-Stream** [comment]
Thank you @Telstra-CDR for your detailed feedback. We will review this feedback and reach out if we have further questions.

**Comment by CDR-CX-Stream** [comment]
Thanks to those who provided feedback on DP267 by 15th September. With the v5 rules out for consultation, the DSB will leave this issue open for comments while considering existing feedback and developing version 2 of DP267, which is expected to be published for consultation in October.

**Comment by perlboy** [comment]
Hi DSB, thanks for leaving this open now that draft rules have been released. While this is being reviewed, just a general comment, if the DSB deems it necessary to alter CX language for `common:*` clusters specifically for Telco please make this an explicitly sector specific authorisation scope instead (eg. `telco:customer.basic:read`). This will avoid a repeat of what was encountered in energy sector.

**Comment by CDR-CX-Stream** [comment]
Thanks again @Telstra-CDR for your feedback. Below are some responses to your queries.

**Individual Customer Data**
- We confirm that mail address relates to postal address.
- While ‘Postal address’ may be more familiar among telco customers, it is also true that terminology may differ by DH and sector. Customer Data is currently treated as common across all sectors. As such, this specific language was considered generic enough to apply across sectors, as it currently does for banking and energy.
- Can @Telstra-CDR advise if it holds data about a consumer's ‘Occupation’?

**Business Consumer Data**
- We confirm that ‘Establishment Date’ relates to the date the organisation described was established. Please refer to [DP 257](https://github.com/ConsumerDataStandardsAustralia/standards/issues/257) on Customer Data Payloads for Telco for more information.
- We acknowledge that ‘Charity Status’ may not be in common APIs in telco. However, it relates to the field ‘isACNCRegistered’ in [DP 257](https://github.com/ConsumerDataStandardsAustralia/standards/issues/257) and is optional.

Other comments are being considered and v2 of DP267 will incorporate any changes.

**Comment by CDR-CX-Stream** [comment]
Thank you @perlboy for your comment. The intention is for customer scopes and language (for `common:customer.basic:read` and `common:customer.detail:read`) to remain common across sectors, including telco, but this feedback will be considered if any divergence is proposed, and it will also be passed on to the technical team.

**Comment by CDR-CX-Stream** [comment]
Version 2 of decision proposal 267 has now been published and can be found in the original post.

Feedback is now open for this proposal and will close on Friday 9 December 2022.

This is intended to be the final consultation on the proposed telco data language standards. Subject to the making of the telco rules, community feedback, and technical standards changes, the Data Standards Body (DSB) will then propose to the Data Standards Chair that these be made into binding data standards. Any further changes will then be considered as part of [standards maintenance](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues).

**Comment by CDR-CX-Stream** [comment]
In line with recommendations from the independent Statutory Review that further time is needed to allow the CDR to mature, the Government has made the decision to pause expansion into superannuation, insurance and telecommunications. The Government also plans to undertake a strategic assessment of the CDR towards the end of 2024 to inform future expansion, including superannuation, insurance and telecommunications, as well as the implementation of action initiation.
 
This consultation will be closed while CDR work on telecommunications is paused. The DSB encourages the telco community to take advantage of this extra time to engage with ongoing consultations that will apply to existing and future sectors. Continued engagement will support cross-sectoral alignment in anticipation of the strategic assessment that will inform future expansion into sectors such as telco.
 
Issues of particular interest to the community are likely to include authentication uplift (see [NP280](https://github.com/ConsumerDataStandardsAustralia/standards/issues/280), [DP211](https://github.com/ConsumerDataStandardsAustralia/standards/issues/211)), [accessibility uplift](https://github.com/ConsumerDataStandardsAustralia/standards/issues/279), [consent review](https://github.com/ConsumerDataStandardsAustralia/standards/issues/273), in which consultation is either ongoing or expected to progress. Other sector-agnostic work of interest can be found [here](https://github.com/ConsumerDataStandardsAustralia/standards/issues) and as part of [standards maintenance](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues).
