### ISSUE TITLE
Noting Paper 280: The CX of Authentication Uplift

### ISSUE THREAD

**Issue by CDR-CX-Stream** [ConsumerDataStandardsAustralia/standards#280]
Following the [Government’s response](https://treasury.gov.au/publication/p2021-225462) to the [Inquiry into Future Directions for the CDR](https://treasury.gov.au/sites/default/files/2021-02/cdrinquiry-final.pdf), as well as the [Independent Information Security Review](https://github.com/ConsumerDataStandardsAustralia/standards/issues/258), the Data Standards Body (DSB) is now conducting Consumer Experience (CX) research to inform which authentication approaches should be supported by the technical and CX standards.

The purpose of this noting paper is to share the DSB’s general CX research approach to authentication uplift with the community. We invite community feedback on this work and recommend you read this noting paper if you would like to:
     • Provide views on the preliminary scope and priorities for authentication uplift
     • Suggest other authentication approaches for the DSB to consider
     • Comment on the general approach to CX assessment of authentication approaches

This paper and consultation will not delve into technical considerations. It focuses on CX research goals and the preliminary scope for authentication uplift, as well as various methods, measures, and metrics being used to assess alternative authentication approaches.

While this paper centres on CX research, the preliminary scope and focus will inform the general scope for CDR authentication uplift. Given the DSB is prioritising authentication uplift as foundational to future CDR expansion including action initiation, community feedback is invited on the preliminary scope and priorities for authentication uplift, as well as any other issues or items that the DSB should consider.

Noting Paper 280 on the CX of Authentication Uplift can be found below:
[Noting paper 280 - CX of Authentication Uplift.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/10216806/Noting.paper.280.-.CX.of.Authentication.Uplift.pdf)

The community is invited to provide feedback on this paper by Friday ~27 January~ 10 February 2023.

-----
Edit: Consultation extended to 10 Feb following community requests

**Comment by CDR-CX-Stream** [comment]
Noting Paper 280 on the CX of Authentication Uplift has now been posted and can be found in the original post.

While this paper centres on CX research, the preliminary scope and focus will inform the general scope for CDR authentication uplift.

Feedback is invited by Friday 27 January 2022.

**Comment by kristyTPGT** [comment]
TPGT appreciates the opportunity to provide feedback in relation to Noting Paper 280, however, we would like to request an extension be provided until Friday 10 February to allow for key stakeholders to be able to participate in the response.

**Comment by perlboy** [comment]
Performing CX research on authentication in _isolation_ from the information security and implementation impacts will result in a potential disconnection from the technical reality. This has already been demonstrated in the course grained scopes, collapsed scopes and fine grained access disclosure variability between the Standards, CX Guidelines and Rules. If nothing else my feedback would be that CX learn from the mistakes of the past so implementers aren't, once again, in a conflict between DSB guidance and Rules.

Additionally, this is a noting paper so there is no _actual_ scope to alter the DSBs approach. Nonetheless I would note that it's a bit rich to publish a paper containing some fairly complex and far reaching research techniques over a holiday break and call it "consultation". On this basis the request of TPGT seems reasonable.

**Comment by CDR-CX-Stream** [comment]
This consultation will be extended to Friday 10 February in response to community requests.

**Comment by CDR-CX-Stream** [comment]
Thanks for your comments @perlboy 

This noting paper was developed following requests from members of the Data Standards Advisory Committee. The aim was to relay how the DSB are approaching CX research on authentication, but also to provide a channel for the community to comment on the initial scope.

The DSB's CX and technical teams worked together on this paper to facilitate alignment. It was published as early as possible once that had been achieved, but we acknowledge the difficulties of consulting in the December-January period. The feedback window has now been extended.

The purpose of this noting paper is to allow the community to provide early input, and we welcome views on any disconnects or negative implications that may have been missed.

**Comment by kristyTPGT** [comment]
TPG Telecom is supportive of the authentication review and agrees with the findings of the Independent Security review that the current OTP method does not meet minimum security requirements. We do not see value in augmenting the current OTP process and believe that the other authentication methods in scope should be considered. The Standards should be updated to provide minimum security requirements for authentication, rather than explicitly prescribing fixed method/s. This is particularly relevant for the Telco sector, as we are already governed by the [Telecommunications Service Provider (Customer Identity Authentication) Determination 2022](https://www.legislation.gov.au/Details/F2022L00548), which outlines how Telcos must undertake Multi-Factor Authentication for high-risk transactions. The Standards should seek to specify the baseline requirement of a framework for authentication that includes:

- a focus on desired outcomes (rather than process);
- an awareness of the effect of other relevant regulatory requirements;
- allows flexibility in how and when businesses use additional authentication measures, to maintain best practices in a constantly evolving security environment;
- provides easy-to-use, flexible approaches to authentication in recognition that one size fits all approaches will impact accessibility for vulnerable consumers; and
- to allow for the expected move towards Action Initiation / Right access in the CDR.

**Comment by anzbankau** [comment]
Thank you for the opportunity to provide feedback. We are broadly supportive of the proposal and note the following for consideration:
 

- Scope to include CX consideration for action initiation and particularly payment initiation. Ideally payments patterns should be resolved before locking down authentication patterns or risk rework. We support a holistic and consistent approach to CX authentication across the breadth of CDR.
- As per previous submissions, the desired action initiation obligation and liability framework may influence preferred security approaches between payment initiators and service providers. As per previous point, A.I. patterns should be an input to CX authentication uplift.
- The security review conducted in 2022 highlighted that the 'current approach to CDR authentication does not meet minimum security requirements'. Is that specific to SMS OTP and not other forms of OTP?
- Will consideration extend to the mooted “expansion of the Digital Identity System” (Statutory Review of the Consumer Data Right Issues paper, Kelly E. March 2022) and its potential impacts to CX? Related point, has a central registry pattern for consumer authentication been considered in light of action initiation complexities? What has the UK experience been and are there lessons we can implement?
- No mechanism exists to ensure that information shared/actions fulfilled by the DH on behalf of a consumer actually relates to the same consumer on the ADR/payment initiator, i.e.:
  - Person A uses Person B’s phone and username to share account data/make payment from Person B’s account without their knowledge (Note that this requires the active consumer (Person A) to have compromised the username & mobile phone of the other person (Person B)).
  - Should there be obligatory verification of customer name (held by DH) at the ADR/service provider end (with appropriate customer consent) as part of A.I. to ensure a more secure system? Of course this is a problem today where consumers only share account data but arguably payments introduces substantially more risk.

**Comment by rjshanahan** [comment]
As a prospective ADR, Tic:Toc welcomes the opportunity to comment on the proposed approach for CX research in relation to the authentication uplift. The experiences that consumers have with authentication are a key driver of CDR conversion rates, which in turn influence commercial decisions about extent and timing of participation in the CDR. 

Tic:Toc supports the security uplift for authentication and the proposed CX research, noting the following points for the DSB’s consideration:

* A key objective of the research should be to test the extent to which leveraging known experiences/patterns could achieve the objectives of increased security and consumer experience. 
    * A new, unfamiliar experience pattern (eg a new biometric authentication process or passwordless security app) may stop a user from completing a consent process and negatively impact consent/conversion. Even more so for use cases involving authentication with multiple data holders. 
    * What are the outcomes in terms of conversion where the authentication process follows an experience pattern the consumer was already familiar with? 
    * This kind of approach would be consistent with the ‘parity principle’ that applies in Open Banking in the UK.
* We agree with an elements-based research approach but note that the way that these elements are tested will be really important. While it is necessary to test individual elements, they need to be tested as part of a complete authentication process (or patterns of elements), which in turn need to be tested in a natural environment for consumers. As an example, consumers are likely to respond differently to an authentication process without context than they are to the same process as part of a home loan application in which they have already provided personal information and built up a sense of trust for the business they are dealing with.
* The data collection methods are varied, which we support, however it is unclear what the scope of the data collection is in terms of sample sizes and which target groups are included. Target groups covered should include a broad range of age groups, those with English as a second language, digital literacy levels groups.
* We are keen to know if there will be an opportunity to see the uplift prototypes and provide feedback before they are tested?

**Comment by commbankoss** [comment]
Please find CBA's feedback attached.
[NP280 submission 10 Feb 23 final.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/10704002/NP280.submission.10.Feb.23.final.pdf)

**Comment by dpostnikov** [comment]
@perlboy made a good point. There is a danger of this research producing something that is either not secure or not implementable.

There is no question that authentication in CDR has to be uplifted and current mechanism is not user friendly or secure.

Noting paper seems to be mixing different things together. I propose to breakdown this problem space into multiple areas, re-assemble it together and only then perform a CX research on the final outcome.

**1. What authorisation flows should be supported?**
- Web-based redirect flow (x2web, web2web)
- App-based redirect flow (x2app, app2app)
- Decoupled flow

UK Open banking, for example, supports all three because they provide appropriate user and use-case coverage (inclusion).

All flows come with different security considerations and have appropriate controls available within FAPI framework that CDR has already adopted, so there is not need to re-invent the wheel. 

The flows that were considered insecure are already ruled out by the community (e.g. embedded).

Picking only one of the flows only creates a bad customer experience, restricts possible use cases and/or prevents a part of the community from using CDR.

Current Australian CDR flow as prescribed by the CDR specifications is a strange, non-standard weak mix of redirect and OTP.

**2. What level of authentication and risk based decisioning is required of different types of transactions?**

This is where we discuss types authenticators, their strength, biometrics multiple factors and FIDO standards (not just Passkeys).

This should be an opportunity to modernise and 	improve authentication across Australian banking, energy and telecommunications industries. 

Frameworks like [NIST](https://pages.nist.gov/800-63-3/sp800-63b.html) should drive what level of assurance is required for a particular use case. We should be encouraging data holders to avoid using knowledge-based secrets and phishable credentials / factors. 

**3. What security and fraud concerns should be considered?**

Movement towards FIDO standards together with transaction signing and risk-based fraud decisioning solves security 			concerns. 

Data holders should be allowed to use existing customer authentication and associated fraud controls. 

**4. What overall customer experience is acceptable?**
The answer to this question should build up on the previous answers.

Overarching principle should always be: Customer shall be using existing and familiar authentication channel with no additional friction.  

Movement towards FIDO standards improves user privacy and authentication user experience. 

Existing CX guidelines and design principles in other jurisdictions can be helpful too, for example, [OBIE CX guidelines](https://www.openbanking.org.uk/wp-content/uploads/2021/04/Customer-Experience-Guidelines.pdf) (UK). 

If you break the problem down as suggested, the right solution might become much clearer, cleaner and we don’t have to re-invent it. 

This has been successfully done before.

**Comment by CDR-CX-Stream** [comment]
Thanks to everyone who provided feedback on the initial scope and approach for CX research into authentication uplift. The DSB will review and consider these comments for ongoing CX research and technical analysis.

Importantly, the CX research is focused on existing and familiar authentication approaches and considering historical learnings from other jurisdictions, such as the UK's OBIE (e.g. [the current guidelines](https://standards.openbanking.org.uk/customer-experience-guidelines/authentication-methods/latest/)). The purpose of the CX research is to understand how and where the existing CDR CX standards and guidelines might need to be adjusted to accommodate these approaches, validate issues with the current state of authentication, and test various community proposals (such as the ‘waterfall authentication’ proposition raised at a [previous Data Standards Advisory Committee](https://consumerdatastandards.gov.au/2020/12/minutes-11-nov-2020) and change requests posted on GitHub).

To support transparency, the DSB will provide links in this thread to published CX of authentication research reports. The DSB is conducting standards analysis in tandem to support any future decision proposals. This thread will remain open so ongoing discussion can take place ahead of any formal consultation on authentication uplift.

**Comment by CDR-CX-Stream** [comment]
The report for the first round of CX of authentication uplift research can be found [here](https://d61cds.notion.site/22Q3-2AU-UPLIFT-R1-One-Time-Password-Research-Report-2694fead22fb46368c1011a7f3c5d0ac).

This report contains findings and considerations based on Round 1 of CX research that was conducted on the ‘Redirect with One Time Password’ (OTP) approach.

**Comment by CDR-CX-Stream** [comment]
The report for the second round of CX of authentication uplift research can be found [here](https://d61cds.notion.site/22Q4-2AU-UPLIFT-R2-App-Browser-to-App-Research-Report-037466c1f57a4cf8ba6e877446d056f1).

This report contains findings and considerations from Round 2 of CX research on ‘App/Browser-to-App with Biometric’.

**Comment by Telstra-CDR** [comment]
We welcome the opportunity to provide feedback and apologies in publishing our feedback later than accepted.   
Broadly, We agree with the purpose and intent of this noting paper and keen to see the outcome of the research. However, Telstra’s view is stronger authentication factors should use pre-existing methods provided by the data holder where possible.
 
        • Telstra and its brands are compliant with authentication requirements for ACMA determination
        • Our customers are used to our existing authentication methods which give customers confidence they are authenticating 
           with Telstra instead of a rogue party.
        • Introducing a differing method will introduce additional friction for our e2e customer experience as our customers may 
          need to use different authenticators depending upon whether they are using CDR or BAU experiences
        • The CDR authenticators and backup methods needs to be managed, as such new self-service capability to manage CDR 
           authenticators may be required introducing additional build requirements for data holders.

**Comment by CDR-CX-Stream** [comment]
To inform the DSB's work for authentication uplift, particularly in relation to offline energy customer support, we are seeking views from the community on the below.

### Context
The redirect with OTP model allows a range of CDR consumers to authenticate to share CDR data. This includes 'offline customers', who are defined as consumers who do not currently have an online account with their data holder. Offline customers are currently only eligible in the energy sector.

As [this article](https://cdr-support.zendesk.com/hc/en-us/articles/4627046759823) outlines, (energy) data holders must not impose additional eligibility requirements, such as requiring an offline customer to register for online account access before they can share data. That is, an offline customer must be able to authenticate to share CDR data using permissible details - such as a unique ID and contact information - already held by the data holder. This means that a consumer without an online account could, for example, use an existing non-digital credential - like an account number - and have an OTP sent to them using contact details already held by the data holder, like an SMS or via email.

Similar scenarios may arise where customers are technically 'eligible' even though they lack an online account with the data holder. The recently published guidance from ACCC on [Eligibility Across DH Brands](https://cdr-support.zendesk.com/hc/en-us/articles/4871126055567) suggests this may occur for multi-banked consumers, but it may also be possible in theory for accounts with multiple parties, such as secondary users, partnerships, joint accounts, and the nominated representatives of non-individuals (particularly in the energy sector).

### The Problem
Deprecation of the redirect with OTP model has been recommended to support CDR security and authentication uplift (see [NP280](https://github.com/ConsumerDataStandardsAustralia/standards/issues/280) and [NP258](https://github.com/ConsumerDataStandardsAustralia/standards/issues/258)). Adopting this approach may have implications for offline customers and a range of energy retailers. Assumptions to be tested include:
- A significant proportion of energy consumers may be 'offline customers'. Based on limited data from major and non-major retailers in 2020:
- an average of 73% of SME customers were offline, which was projected to reduce to 58.5% in 2021
- an average of 49% of residential customers were offline, which was projected to reduce to 40% in 2021
- As such, deprecating the redirect w/ OTP model will effectively 'switch off' support for a non-trivial amount of CDR consumers who are currently eligible as per the rules and able to share CDR data today
- Some energy DHs may not provide online portals at all, meaning all of their customers are 'offline customers'
- Energy retailers mandated to share CDR data have been implementing CDR even if a significant proportion of, and in some cases all of, their customers are offline customers (which may apply to DHs in other sectors for certain scenarios described above)

Alternatively, risks and limitations of the OTP model for offline customers are assumed to include:
- Delivery of an OTP to an unverified contact detail, such as a mobile or email, which may be further complicated by lower levels of identity proofing for energy customers compared to banking
- This is further complicated by the low level of identity proofing for energy customers
- "Unique IDs" that may not be unique to the offline customer
- Single-factor OTP does not currently meet the assumed data sensitivity requirements for CDR data sharing. At present, the current authentication requirements for offline customers map to Credential Level 1 (CL1) as defined by the Data Transformation Agency's (DTA) Trusted Digital Identity Framework (TDIF). TDIF states that CL1 must only be used where risk of compromise will result in "negligible to minor consequences to the Individual or the service".
- Additional stronger security measures for offline customers are limited without a registered digital identity

### Working hypotheses
The current hypothesis is that the redirect with OTP model may be a critical fallback option for less digitally mature sectors, as well as for offline customers. However, recommendations have been made for redirect with OTP to meet CL1-2 if not be deprecated entirely.

For customers with online accounts, achieving CL2 using redirect with OTP may be possible. For offline customers without online accounts, CL1 may be possible. If CL3 is required for action-initiation, it is unlikely that offline customers will be able to participate.

### Questions for consultation
The DSB is seeking community input on the risks, tradeoffs, and implications of:
- retaining the current redirect with OTP for offline customers;
- deprecating redirect with OTP entirely; or 
- requiring that the redirect with OTP model meet a higher credential level (e.g. CL2)
- pursuing an alternative to maintain support for offline customers

Input should consider security risks, consumer experience, as well as the costs and implications for DHs, particularly in energy, who have been, or are in the process of, implementing the current model to support authentication for offline customers.

The following questions may be used to guide responses:
1. How might we augment the redirect w/ OTP flow/mechanism to maintain support for offline energy customers?
2. If it is not appropriate to retain the redirect w/ OTP flow at all, what alternatives exist to maintain support for offline energy customers?

**Comment by AGL-CDR** [comment]
Hi DSB et al, with respect to timeframes, can I please ask that the above request for feedback be updated with a date that consultation closes? Also, there is chance for confusion here given the request is nested within the comments section of another request for consultation, which has since closed. Would it be appropriate for this new request to be separated into a new issue card, linking back to #280?

**Comment by CDR-CX-Stream** [comment]
@AGL-CDR the problem space has now been converted into a separate consultation, [Noting Paper 296](https://github.com/ConsumerDataStandardsAustralia/standards/issues/296), which is now open for feedback until Monday 17 April.

**Comment by CDR-CX-Stream** [comment]
A fourth report on the CX of authentication uplift research has been published online and can be found [here](https://d61cds.notion.site/23Q2-2AU-UPLIFT-R1-3-Comparison-Report-6fee0fa6dc914636aa7a2a1977c1061f).

This report contains summaries and comparisons of all the recent CX research conducted on this topic, including an improved Redirect with OTP flow; App/Web to App with Biometrics; Decoupled with QR Code. 

In total, over 150 consumers participated across the three rounds of research; which involved 90-minute 1:1 interview sessions and 30-minute unmoderated prototype tests.

**Key Themes**
Virtually all research hypotheses were validated in this research. Key qualitative themes from consumer participants also highlighted that:
• Friction is multifaceted
• Users look for, and rely on, visual trust markers to assess risk
• Extra authentication factors are appreciated
• Meeting consumer expectations helps build trust
• Step-up authentication is perceived as the norm
• Supporting those experience vulnerability is important

**System Usability Scale**
App/Web-to-App was the best performing model when it came to System Usability with a score of 82.88, followed closely by Redirect with One Time Password, which scored 82.61. Decoupled scored slightly lower at 74.29, but this is still an above average score.
<img width="998" alt="SUS CX Auth Uplift" src="https://github.com/ConsumerDataStandardsAustralia/standards/assets/44986761/10fd2470-f096-4a7b-87d6-51a74fe2ed87">
_N.B. The average SUS score for technology in general is 68. Usability scores above 80 are considered well-performing; scores around 68 are considered average and may require improvement; and scores below 51 are considered poor._

**Opportunities**
There was a clear desire for App/Web-to-App to be supported, affording consumers the option to authenticate within their DH app. 

The research on Redirect with One Time Password identified several key [opportunities and improvement areas](https://d61cds.notion.site/22Q3-2AU-UPLIFT-R1-One-Time-Password-Research-Report-2694fead22fb46368c1011a7f3c5d0ac#13cc387d93b5436bb00b1a84fe43c703) and could be uplifted to continue being a supported model, particularly for sectors with lower digital adoption. 

Decoupled could also be supported to allow the user to authenticate securely with their known device no matter how they interact with the CDR, while support for the use of QR codes as part of CDR authentication could be de-prioritised.

**Next Steps**
The DSB are now working on an initial Decision Proposal to consult on the step-up and waterfall authentication approach. 

Authentication uplift will also need to consider Credential Level pairings and recommendations from both the [PwC IC Accessibility](https://github.com/ConsumerDataStandardsAustralia/standards/issues/279) and [Independent Security Review](https://github.com/ConsumerDataStandardsAustralia/standards/issues/258) reports.

The DSB will present on the topic of authentication uplift at the CDR Implementation Call on Thursday 13th July from 3pm-4:30pm. This session will cover key findings and opportunities from the CX research along with a brief overview of the DSB's approach to CDR authentication uplift. You can register for the regular call by emailing contact@consumerdatastandards.gov.au - see [here](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-Consumer-Data-Right-Implementation-Call) for further details about the call.

**Comment by CDR-CX-Stream** [comment]
Attached to this comment is the slide deck the CX Team presented at the Implementation Call on Thursday 13th July.

[Implementation Call Presentation - Authentication Uplift Research Outcomes.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/12067092/Implementation.Call.Presentation.-.Authentication.Uplift.Research.Outcomes.pdf)

The deck contains high-level summaries and comparisons of all the recent CX research conducted on this topic, Redirect with OTP flow; App/Web to App with Biometrics; Decoupled with QR Code. It also shares the DSB's current thinking on the authentication uplift approach, which will be formally consulted on as a Decision Proposal soon. 

This thread will be updated when the DP is live.

**Comment by CDR-CX-Stream** [comment]
This issue has now been closed. The authentication uplift work has now progressed into the decision proposal phase. Please see https://github.com/ConsumerDataStandardsAustralia/standards/issues/326 and https://github.com/ConsumerDataStandardsAustralia/standards/issues/327 for the ongoing consultations regarding authentication uplift.
