### ISSUE TITLE
CDR Australia Common API Query

### ISSUE THREAD

**Issue by SheejaSobyV** [ConsumerDataStandardsAustralia/standards#283]
The unauthenticated API in Common APIs called Get Status (https://consumerdatastandardsaustralia.github.io/standards/#get-status ) mentions "Obtain a health check status for the implementation" , Few queries here:

What do we mean by implementation ? Does it mean we need to in real time we have to check the health of every CDR API (is it available or not based on "200" OK response)  or just give information of the fact that if all the APIs (lets say Telco APIs) are implemented  and available for consumption ?

Also is detectionTime and expectedResolutionTime mandatory in ResponseCommonDiscoveryStatus (https://consumerdatastandardsaustralia.github.io/standards/?examples#tocSresponsecommondiscoverystatus)  if there is PARTIAL_FAILURE or UNAVAILABLE

Regards,
Sheeja

**Comment by CDR-API-Stream** [comment]
Hi @SheejaSobyV, queries like this are intended to be raised and dealt with on the [CDR Support Portal](https://cdr-support.zendesk.com/).  You can also search here for answers to your questions, many have which may have been asked by participants in the past.

For instance, in answer to your question, here are some articles that would be helpful:
- [Get status payload fields](https://cdr-support.zendesk.com/hc/en-us/articles/900005173683-Get-Status-Payload-Fields)
- [Definition of status and how health check status can be determined?](https://cdr-support.zendesk.com/hc/en-us/articles/900003123023-Definition-of-status-and-how-health-check-status-can-be-determined-)

If these articles, or others, don't answer your questions feel free to raise a new ticket which will lead to a new article.

We reserve this issue tracker for consultations on changing the standards so I will close this thread.
