### ISSUE TITLE
Decision Proposal 302 - Telco Draft Feedback Cycle 2

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#302]
This is a placeholder for an upcoming consultation

**Comment by CDR-API-Stream** [comment]
This consultation thread has been raised to allow for holistic feedback to be provided on the draft telco standards as a whole.

The [draft telco standards](https://consumerdatastandardsaustralia.github.io/standards/#telco-apis) (which are draft only and non-binding) can be found on the standards site at:
https://consumerdatastandardsaustralia.github.io/standards/#telco-apis

Feedback is now open on any issue related to the draft. This thread will remain open until further notice. At that time proposed changes will be incorporated.

**Comment by kirkycdr** [comment]
For TelcoUsageMessagingMms the description for "international" should be "**Num**ber of international MMS messages sent"

**Comment by CDR-API-Stream** [comment]
In line with recommendations from the independent Statutory Review that further time is needed to allow the CDR to mature, the Government has made the decision to pause expansion into superannuation, insurance and telecommunications. The Government also plans to undertake a strategic assessment of the CDR towards the end of 2024 to inform future expansion, including superannuation, insurance and telecommunications, as well as the implementation of action initiation.

This consultation will be closed while CDR work on telecommunications is paused. The DSB encourages the telco community to take advantage of this extra time to engage with ongoing consultations that will apply to existing and future sectors. Continued engagement will support cross-sectoral alignment in anticipation of the strategic assessment that will inform future expansion into sectors such as telco.
