### ISSUE TITLE
Decision Proposal 317 - ‘Buy Now, Pay Later’ Product and Account Detail

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#317]
This Decision Proposal seeks feedback on proposed changes to the Standards to support Buy Now, Pay Later products.

[Decision Proposal 317 - Buy Now Pay Later Product and Account Detail.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/12471275/Decision.Proposal.317.-.Buy.Now.Pay.Later.Product.and.Account.Detail.pdf)

Consultation on this proposal will close on **Friday 6 October 2023**.

**Comment by CDR-API-Stream** [comment]
The [opening comment](https://github.com/ConsumerDataStandardsAustralia/standards/issues/317#issue-1809137947) has been updated and the Decision Proposal is now attached. 

 The Data Standards Body welcomes your feedback.

**Comment by CDR-API-Stream** [comment]
Please check out [our short video on Decision Proposal 317](https://youtu.be/IE9CutmCNYw?si=D0SFGmC7jcDUyLnj)

**Comment by commbankoss** [comment]
Hi @CDR-API-Stream,
 
Thank you for providing us the opportunity to respond to Decision Proposal 317 on Buy Now, Pay Later Product and Account Detail. 

We respectfully request an extension of the submission time, to Friday 20 October 2023, to finalise our submission.
 
Kind regards,
CBA Team

**Comment by CDR-API-Stream** [comment]
The timeframes to conduct the initial standards consultations for NBL are tight if we are to define a set of standards and allow for maximum lead time for implementation planning and execution.  We have also indicated that there will be more opportunity to provide feedback before the standards are put to the chair for a decision.  A follow up round of consultation holistically considering draft standards that incorporate all of the feedback to date will be conducted once this consultation is complete.

For these reasons we are not extending this consultation.

**Comment by perlboy** [comment]
12 months is considered "tight" now? 🤯

**Comment by Australian-Finance-Industry-Association** [comment]
Hi @CDR-API-Stream,

AFIA appreciates the opportunity to provide feedback to DP 317.

We concur with @commbankoss and would like to request a short extension of the submission deadline, given the current context of multiple parallel and interrelated consultations.

A short extension would enable us to provide more fulsome and useful feedback to the Design Proposal.

Kind regards,
AFIA

**Comment by NationalAustraliaBank** [comment]
Hello @CDR-API-Stream, 

NAB appreciates the opportunity to provide feedback to DP 317. We would also like to request an extension for this submission as we are in the process of submitting feedback for other consultations which are also due shortly.

Regards,
NAB

**Comment by CDR-API-Stream** [comment]
We will leave this consultation open for a couple of days into next week to allow for any last minute submissions to be finalised and submitted.

**Comment by ShannonRennie** [comment]
Hi @CDR-API-Stream, 

Thank you for the opportunity to provide feedback. Please find attached Basiq's response to the decision proposal

Kind regards, 
Shannon 

[Decision Proposal 317 – Basiq response.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/12827247/Decision.Proposal.317.Basiq.response.pdf)

**Comment by Australian-Finance-Industry-Association** [comment]
Dear @CDR-API-Stream, 

We thank you for your consideration in extending the time available for consultation. 

Please see attached our detailed comments in respect of Decision Proposal 317. 

Kindest regards, 

[Final Submission - Decision Proposal 317.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/12853301/Final.Submission.-.Decision.Proposal.317.pdf)

AFIA Team

**Comment by commbankoss** [comment]
Hi @CDR-API-Stream 

Please find attached CBA's submission for DP317

Kind regards

CBA
[20231010 CBA Group Submission Decision Proposal 317.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/12854032/20231010.CBA.Group.Submission.Decision.Proposal.317.pdf)
