### ISSUE TITLE
Maintenance Issue 599 - Inclusion of the change of Get Metrics authorisations property from optional to mandatory

### ISSUE THREAD

**Issue by MrWoo16** [ConsumerDataStandardsAustralia/standards#332]
The CDS v1.27.0 published on 10 October 2023 includes a change that updates the Get Metrics v4 & v5 authorisations property from optional to mandatory.  This change has been classed as a minor non-breaking change within Maintenance Issue 599.  

However we have, and I'm sure other data holders will have done the same, based our new Get Metrics v4 response on the direction in CDS v1.25.0 that confirmed the new authorisations property was optional, with the assumption that the individual metrics under this property would be mandatory if the authorisations property was returned.

As the ACCC / CDS deadline to implement Get Metrics v4 is the 1 November 2023 we have taken the approach at this time to emit the authorisations property from the v4 response, as the collection of all the required authorisations, revocations and expiry metrics for population within the GET Metrics API response requires significant re-development and enhancements.

Again I'm sure we are not alone with this approach and development requirement with the assumption that a number of data holders will be facing the same non compliance issue as a result of this 'simple' wording change.

The section within Maintenance Issue 599 confirms:

_The authorisations property in Get Metrics v4 and v5 is marked as optional. This may have been intended to be mandatory as per most other top-level properties_.

Can you please advise whether the authorisations property was intended to be optional or mandatory as the original Decision 288 –Non-Functional Requirements Revision does not provide any clear direction on this.

Apologies if this has been covered elsewhere rather than CDS v1.25.0 and Decision 288 –Non-Functional Requirements Revision

**Comment by MrWoo16** [comment]
Apologies I've just realised that I've incorrectly created this issue on the standards repository rather than the standards maintenance repository.  

As I've replicated this issue on the standards maintenance repository please feel free to delete or close the issue.  However, the importance and impact of the wording change implemented as part of v1.27.0 still applies.

**Comment by CDR-Engagement-Stream** [comment]
Raised in Standards Maintenance as [Issue 617](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/617)
