### ISSUE TITLE
Decision Proposal 041 - Feedback On Product Reference Data

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/standards#41]
During the previous round of holistic feedback on the full draft standards the feedback on product reference data was extensive but also conflicting.  While the structure is now considered settled (ie. a generic rather than strongly typed) the details of the features and conditions is not.

Rather than seek to synthesise all of the feedback independently this thread has been created to focus community feedback on the product reference payloads to generate more alignment amongst stakeholders.

After meeting the members of the ABA I anticipate that specific proposals will be posted here to help move the payload forward.  Rather than waiting until the end of the feedback period and then responding to all feedback at once I intend to be a more active participant in this thread.

Note that the list of categories for the productCategory field should be considered in scope for this thread. 

-JB-

**Comment by bazzat** [comment]
ANZ, CBA, NAB and Westpac have, with the facilitation of the ABA, developed some detailed proposals for modifying product reference data in the following areas:
- Fees
- Tiering
- ProductCategory
- Bundling

These proposals are "best efforts" created in a short time frame and should not be considered definitive or complete, however they do have the broad support of all four of the contributing banks.

Please see the attached PDF:
[Product Reference Data Proposals.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/2679137/Product.Reference.Data.Proposals.pdf)

**Comment by bazzat** [comment]
Submission from ANZ, CBA, NAB and Westpac updated to include Bundling.

[Product Reference Data Proposals updated.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/2684131/Product.Reference.Data.Proposals.updated.pdf)

**Comment by da-banking** [comment]
We have reviewed the product reference data proposal from the ABA and the major banks. We broadly support the recommendations made regarding Fees, Tiering, Product Categories, and Bundles.

Some analysis:

**Proposal 1: Fees**

***Product Fee Types***
We thought it worth defining a `WITHDRAWAL` as withdrawing cash from the account via an ATM or over the counter; and defining a `PAYMENT` as an electronic transfer of funds from one bank account to another.

We have much finer grain to the underlying data than the proposed categories describe. We imagine that all banks will have much more detailed data than the proposals, and that it may be to the benefit of consumers to include that detail in product comparisons. As it currently stands, we would map fees in as follows:
*WITHDRAWAL*:
* ATM Withdrawal
* OTC Withdrawal
* EFTPOS With Cashout
* Visa Cash Withdrawal (domestic, and international)
* Bank @Post Withdrawal

*PAYMENT*:
* NPP sct, x2p1, ...
* Direct Entry
* BPay
* Intra bank
* Cheque
* ATM (between accounts)
* International Transfers

*DEPOSIT*:
* OTC Cash
* OTC Cheque
* Bank @Post Cash
* Bank @Post Cheque
* ATM Cash
* ATM Cheque
* NPP sct, x2p1
* BPay Biller
* Visa Deposit

We would also suggest an additional value for `PURCHASE`. Purchases are electronic transactions between an account and a merchant.

*PURCHASE*:
* EFTPOS
* Visa (inc. the pays)

Absent a `PURCHASE` enum type, we will map these into `PAYMENT`.

***Discount Eligibility***
Absent first class representation, we would place the following discount eligibilities that we support in the `Other` category:
* RELATIONSHIP_VALUE - the value of the relationship the bank has had with the customer 
* RELATIONSHIP_LENGTH - the duration of the relationship the bank has had with the customer
* EMPLOYMENT_SECTOR - the discount is available to members of certain industries
* CLUB_MEMBERSHIP - the discount is available to members of a certain club for example Qantas Frequent Flyer
* PRODUCT_BUNDLE - the discount is available to holders of other products as part of 

*Proposal 2: Tiering*

***Recommended Option: 1 – Generalised TierBand Structure***
`tierValueMinimum` and `tierValueMaximum` are breaking with all other durations not using the ISO8601 duration format, and it doesn't seem to be an accident given the comment `// Note: generic, not "P11M"`. We are confused about the reasoning here. Use of the ISO8601 format would be maximally flexible, and would eliminate the need for the `tierUnitOfMeasure` property.

*Proposal 4: Bundling*
We support the recommendation to support bundling as a first-class endpoint.

We have mentioned in earlier feedback of the need for a _whole of relationship_ view when discounting products. This can be seen as a form of bundling, though perhaps less formal than is envisaged in this recommendation.

**Comment by anzbankau** [comment]
Hi 
@JamesMBligh Considering product data is the first cab off the rank we are keen to understand the ETA of the next version of the product API?

**Comment by anzbankau** [comment]
@da-banking re: Proposal 2: Tiering
RateTierType is generalised to support any current or future 'unit of measure' - not just days or months (or years). In the description of tierUnitOfMeasure the other examples are 'DOLLAR' and 'PERCENT'. In that sense, using Duration is actually less flexible.
Also, using tierUnitOfMeasure = 'DURATION' instead of 'MONTH' and 'DAY' would require tierValueMinimum and tierValueMaximum to have ISO 8601 values like 'P11M'. This would violate the simple 'number' data types.
A Unit of Measure field with associated numeric field(s) is a common generalisation pattern.

**Comment by JamesMBligh** [comment]
Happy New Year everyone.  Thanks for the feedback to date, especially the comprehensive feedback from the Banks.  There is a lot to ingest here but I am aware that implementation teams are waiting for resolution for the Product payloads.  I intend to respond substantively in the next 24 hours and will then leave this thread open for a week to allow for a response.

-JB-

**Comment by JamesMBligh** [comment]
Hi All,

Due to the support needed for some internal changes and other parts of the regime I haven't been able to formalise the decisions above into swagger and documentation.  This work is in process and I hope that there will be something public in the next day or so.

-JB-

**Comment by anzbankau** [comment]
Hi James, 
Along with the swagger and documentation for public product we would also need the NFR information and other requirements i.e. performance, reporting and admin endpoints. Are you expecting this will be delivered with the swagger?

**Comment by JamesMBligh** [comment]
Sorry @anzbankau, I just realised I have not yet responded to the NFR thread.  This accidentally came off my todo list because I thought I had already responded.  I will do this as a priority.

I'll also close this thread and move further comments to feedback cycle 4 (issue #48)

-JB-
