### ISSUE TITLE
Need Clarification on Transaction Reference in Transactions End Point  (GET /banking/..../transactions)

### ISSUE THREAD

**Issue by Apptimus** [ConsumerDataStandardsAustralia/standards#47]
We are planning to extend one of our Systems to communicate with your API.  Please clarify the following.

1. What do "reference" and "description" fields mean in Transactions End Point?. Can that be explicitly given by the payer at the time of the transaction?. 

2. What does "payer" field in Single Transaction End Point (GET /banking/..../transactions/{trans ID}) denote?.

3. Will "Transaction ID" be provided to the payer at the time of the payment? - So that we can use that as the synchronization field in our system transactions.

Thank you.

**Comment by JamesMBligh** [comment]
Excellent questions.  For the API Standards repo, however, we are collating feedback via common issue threads.  Please raise your question through one of these :)

-JB-
