### ISSUE TITLE
Decision Proposal 057 - Direct Debit Authorisations v1

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/standards#57]
This issue has been opened to propose and publish the final decision paper for Direct Debit Authorisations that establishes version 1 of these end points and payloads.

The proposed decision is below.  Feedback will close on 19th April.
[Decision 057 - Direct Debit Authorisations V1.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/3123419/Decision.057.-.Direct.Debit.Authorisations.V1.pdf)

**Comment by JamesMBligh** [comment]
Please note that the decision proposal for this item has been added to the issue description

-JB-

**Comment by NationalAustraliaBank** [comment]
NAB would like to provide the following initial feedback on the Direct Debit Deductions v1 definition.

#### Deductions versus authorisations
Noting that the ACCC rules refers to direct debit deductions and continuing the conversation from Data61's previous comment https://github.com/ConsumerDataStandardsAustralia/standards/issues/44#issuecomment-458392774, would it be more consistent for data holders to return deductions that have been identified as direct debits in the last *x* months[1]? 

This is an alternative to the current proposal that requires each data holder to attempt to inconsistently derive an authorisation agreement and return the last debit under that derived authorisation.

[1] Pending ACCC rules data extents definition.



#### `authorisedEntity` object
Is the `description` field is missing a mandatory definition? We assume it is mandatory given that this field can now represent the narrative of the transaction.

**Comment by anzbankau** [comment]
Hi James 
Just one minor point on direct debits, it would be great if “description” and “FI” fields could have sample values and conform to some standards. There is concern that the free format nature of these values will have limited values for the data consumers and customers.

**Comment by JamesMBligh** [comment]
Response to feedback is as follows:

- The point regarding derivation of direct debits is understood but the change to turn authorisations into a list of direct debits makes the data returned inconsistent with the intent and would not be aligned to the ACCC rules by the understanding of the DSB.  It would also make the scheduled payments scope give access to limited transaction data which would be problematic for consent language. Essentially the position is that instead of obtaining a list of previous direct debits the most recent debit is identified and the authorisation is derived as well as possible from that.  In addition, a DIRECT_DEBIT type has been added to transactions to allow for filtering of direct debits if that is required by a specific use case.  In light of this the model will not be changed.
- The description field has been corrected to be mandatory.
- The application of standards to the description and FI fields has been considered but the issue with this is that the ability to conform to any specific standard is dependent on how the debits themselves pass through BECS and that is not comprehensively understood.  The current position is that the fields will be left open and more formatting will be applied in a subsequent version if an consistent standard emerges.  It would seem too early to predict what that standard might be.

The document in the main comment of this issue has been updated and swagger has been updated.  The swagger updates will be published once all v1 feedback is incorporated.

-JB-

**Comment by JamesMBligh** [comment]
Please find attached the final decision covering this issue
[Decision 057 - Direct Debit Authorisations V1.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/3251496/Decision.057.-.Direct.Debit.Authorisations.V1.pdf)
