### ISSUE TITLE
Need clarifications regarding the use of x-v, x-min-v and x-<PID>-v headers

### ISSUE THREAD

**Issue by dimuthnc** [ConsumerDataStandardsAustralia/standards#60]
In the 2018 Christmas working draft, we have noted the use of **x-v** and **x-min-v** and **x-PID-v** header parameters (which are intended to determine the version of the request/response). As we understood, data holders are supposed to provide support for these HTTP headers in all consumer API endpoints. On the other hand, it is required to specify the API version as a path parameter (in each endpoint). In a conflicting scenario, how should we prioritize which version to use? 

As an example, consider the below scenario. 

> Let's assume we have published version V5, V6, and V7 of a Banking API. Now a request comes with below parameters. 
> 
> Request path -  www.somebank.com/cds-au/V7/banking/accounts
> 
> Value of x-v header - V6
> Value of x-min-v header - V5
> 

In the above scenario, if we only consider the x-v and x-min-v headers, we should respond according to the V6 version( highest supported version between x-min-v and x-v). But if we consider the Request path, we need to respond according to the V7 version. How to proceed in such a conflicting scenario?

On a separate note, we have noted the proposed discoverability API[1]. Once we have this API, we can simply use that to discover available API versions. If so, as a data recipient, do I still need to use this x-v, x-min-v or x-PID-v headers?

[1] - https://github.com/ConsumerDataStandardsAustralia/standards/issues/19

**Comment by JamesMBligh** [comment]
Hi @dimuthnc, for this repo it is preferred if new issues are not raised and instead queries are raised as comments via the various open threads.  In this case this query would be appropriate in the holistic feedback thread #52.

I will repost your query on that thread and respond there.

-JB-
