### ISSUE TITLE
Decision Proposal 061 - Client & Customer Authentication

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/standards#61]
This issue has been opened to capture, document and obtain feedback on a subset of the Information Security profile for the CDR regime with a view to finalisation and endorsement by the Chair of the Consumer Data Standards body.

This issue is specifically related to authentication considerations for accredited data recipients and customers.

The decision proposal is attached below. Feedback will be closed on 17th May.
[Decision Proposal 061 - Client & Customer Authentication.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/3134429/Decision.Proposal.061.-.Client.Customer.Authentication.pdf)

**Comment by JamesMBligh** [comment]
The decision proposal has been published above.

-JB-

**Comment by NationalAustraliaBank** [comment]
NAB is broadly supportive of this decision which in nature is a re-hash of the InfoSec standards. We are interested in understanding how DR certs will be issue, exchanged and maintained without the aid of Dynamic Registration.

**Comment by JamesMBligh** [comment]
Thanks for all of the feedback. By request this issue will be kept open for further consultation until mid week.

**Comment by commbankoss** [comment]
Mechanisms of MTLS
Summary:
Commonwealth Bank would like to see more explicit definitions before closure of Decision Proposal 61, specifically regarding the language used to describe the mechanisms of MTLS (decision proposals 61 and 65 appear to differ).
 
Detail:
CBA requires greater clarity regarding the use of MTLS during a data request. Decision proposal 61, suggests private_key_jwt should be used for client authentication for all channels (i.e. front channel and back channel). It also states  “The PKI Mutual TLS OAuth Client Authentication Method SHALL not be supported”. However, decision proposal 65 states “MTLS MUST be supported as a Holder of Key Mechanism and MTLS Holder of Key allows issued tokens to be bound to a client certificate as specified in section 3 of [MTLS] (OAuth 2.0 Mutual TLS Client Authentication and Certificate Bound Access)”. 
 
The documentation should explicitly state what Standard of MTLS is used and how it is implemented. 
 
CBA believes that the definition of Client Authentication and Certificate bound access tokens (with a single private key certificate used for proof-of-possession) should be aligned to the specification outlined in OAuth 2.0 Mutual TLS to provide clarity to participants.
 
CBA also seeks clarity regarding the instances when private key certificate should be bound to issued tokens. It is our expectation that if client authentication is carried out using private_key_jwt, MTLS must be used as holder of key mechanism and that issued tokens are bound to the client certificate in every instance of consumer data exchange. 
 
Further clarity is also sought regarding which resource endpoints are intended to use private_key_jwt for client authentication. 
 
Levels of Assurance
Summary:
We are supportive of a level of assurance (LOA) of 3 for WRITE operations but require more clarity regarding which operations are considered WRITE. That said, Commonwealth Bank considers this a change to the previous standard. We recommend that Data61 consider the E2E experience for this operation given we consider it a poor customer experience to step up within the consent flow.
 
Detail:
Commonwealth Bank seeks clarity regarding which operations are considered WRITE. Commonwealth Bank is supportive of using LOA of 3 in the future but require time to consider implementation options. 
 
The Decision Proposals state: 
“At least an LoA of 3 has been achieved during the establishment of consent” and 
"At least an LoA of 2 has been achieved during the establishment of consent and a subsequent challenge/response has resulted in an LoA of 3 being achieved within the lifespan of the current Access Token."
 
Commonwealth bank believes that given the grant or modification of consent is a WRITE operation to an external party and therefore should in all cases originate as LoA of 3.

**Comment by JamesMBligh** [comment]
To clarify regarding WRITE operations, currently the standards do not include any WRITE operations.  These statements are included purely to accommodate future extension, either through an expanded designation instrument or through voluntary extension by a Bank.

Other feedback will be reviewed internally.  I'll be closing down feedback on this thread.  Any additional feedback or points of clarification can be posted on the current open thread for feedback (#67)

**Comment by JamesMBligh** [comment]
Referring to the mechanism of MTLS, this is aligned with the position taken in the UK Open Banking Security profile.  Specifically in reference to the following sections:

> #### 6.2.1 Protected resources provisions
>The resource server with the FAPI endpoints
>
>   1. shall mandate mutually authenticated TLS;
>   1. shall verify that the client identifier bound to the underlying mutually authenticated TLS transport session matches the client that the access token was issued to;

and...

> #### 5.2.2 Authorization Server
> The Authorization Server
> ...
> 7. shall authenticate the confidential client at the Token Endpoint using one of the following methods:
>    1. `tls_client_auth` as per [MTLS] (Recommended); or
>    2. `client_secret_basic` or `client_secret_post` provided the client identifier matches the client identifier bound to the underlying mutually authenticated TLS session (Allowed); or
>    3. `private_key_jwt` or 'client_secret_jwt` (Recommended);

The only change for the CDR profile is to constrain client authentication to use private_key_jwt.  The language used will be re-examined as this is not being made clear currently.

**Comment by JamesMBligh** [comment]
Please find attached the final decision covering this issue
[Decision 061-066,068 - Information Security Profile.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/3251488/Decision.061-066.068.-.Information.Security.Profile.pdf)
