### ISSUE TITLE
Decision Proposal 063 - Normative References

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/standards#63]
This issue has been opened to capture, document and obtain feedback on a subset of the Information Security profile for the CDR regime with a view to finalisation and endorsement by the Chair of the Consumer Data Standards body.

This issue is specifically related to describing the normative references that underpin the security profile.

The decision proposal is attached below.  Feedback will be closed on 10th May.
[Decision Proposal 063 - Normative References.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/3169910/Decision.Proposal.063.-.Normative.References.pdf)

**Comment by JamesMBligh** [comment]
The decision proposal has been published.

-JB-

**Comment by JamesMBligh** [comment]
In response to internal feedback within the DSB I have modified the UUID normative reference to specifically imply the use of UUID version 4.  The proposal in the main comment has been updated.

-JB-

**Comment by WestpacOpenBanking** [comment]
The [FAPI-RW] and [OIDC] normative references have explicit references to client registration and validation against information provided at registration. For this reason we draw attention to our comments on [Dynamic Client Registration](https://github.com/ConsumerDataStandardsAustralia/infosec/issues/63#issuecomment-489017778).

**Comment by JamesMBligh** [comment]
@WestpacOpenBanking a response to your linked comment has been provided in the InfoSec issue referenced.

In summary, dynamic registration will not be supported by Data Holders.  Data Recipients will register with the ACCC Register and then Data Holders will obtain registration data from the Register.

**Comment by commbankoss** [comment]
Commonwealth Bank is broadly supportive of Decision Proposals 63 and 65. However, to fully endorse the Information Security Decision Proposals we would like to see all the proposed decisions to understand how the various elements interact. It is crucial to look at the full end-to-end journey. 
 
Commonwealth Bank also notes that decisions made in other streams (e.g. CX) may require us to revisit these decision proposals in the future in the event they impact one another.

**Comment by NationalAustraliaBank** [comment]
NAB is supportive, although would like to see a statement included that where the CDR rules have resulted in customisation, that this explicitly overwrites the normative references as part of this decision proposal.

**Comment by JamesMBligh** [comment]
The proposal has been amended in the main comment to accommodate the changes accepted in previous comments.  Specifically, a comment has been added to indicate normative references are applicable unless overridden by other proposals.

This issue has now been locked and a final decision document will be drafted for consideration by the Chair.

**Comment by JamesMBligh** [comment]
Please find attached the final decision covering this issue
[Decision 061-066,068 - Information Security Profile.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/3251482/Decision.061-066.068.-.Information.Security.Profile.pdf)
