### ISSUE TITLE
Decision Proposal 064 - Scopes, Claims & Tokens

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/standards#64]
This issue has been opened to capture, document and obtain feedback on a subset of the Information Security profile for the CDR regime with a view to finalisation and endorsement by the Chair of the Consumer Data Standards body.

This issue is specifically related to scopes, claims and tokens.

The decision proposal is attached below.  Feedback will be closed on 10th May.
[Decision Proposal 064 - Scopes, Claims & Tokens.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/3169902/Decision.Proposal.064.-.Scopes.Claims.Tokens.pdf)

**Comment by JamesMBligh** [comment]
The decision proposal has been published.

-JB-

**Comment by ralphbragg-ob** [comment]
Hi, 

Just a quick question from me, given that it's possible to simply introspect a refresh token from the introspection endpoint. Was the standard way of finding out additional information about a token considered as a proposal? In the UK, the model proposed here was challenged by vendors as not standard or supportable even though it's sensible. Have we had the vendors weigh in as i'd be keen to see this standardized globally.

See comments from UK Decision Log - i'd welcome any updated information

Option | Description | Pros | Cons | Notes
-- | -- | -- | -- | --
1 Use OIDC expires_in field | Use the expires_infield in the OIDC token response. ASPSPs must return this value.The parameter is 'RECOMMENDED' in OAuth. The proposition is that make this a mandatory parameter as part of the token response. | The period of time for which an access token is valid is communicted through the expires_in field that is returned as part of the token response. This is standard OAuth.Trivial implementation and potentially OOTB for most vendors | Does not fully address the requirements as it does not indicate when the refresh token expiresWhen evaluating the response from ASPSPs that issue refresh tokens, this value is meaningless to the TPP |  
2 Add new field in Payload | In the consent payload add a new element to indicate the expiry date of the token | Addresses the requirement | Conflates information between the application and security layerMay be complex to implement in ASPSPs where clean seperation between layers has been put in place |  
3 Use Id_token claim | Use a claim in the id_token to indicate when the refresh token would expire, in addition to OIDC expires_in field for access token expiry | Addresses the requirementAll within OIDC standards - nothing in the application space | If the expiry date on the refresh token is adjusted for whatever reason, the id_token would need to be regenerated and a means would have to be provided (e.g. userinfo end-point) to re-retrieve the id_token | There are no standard OIDC claims to express this. We will need to create a custom claimWhere an ASPSP does not issue a refresh token, the claim should not be populated
4 Use the token introspection end-point | Use an extension to token introspection end-point to introspect the refresh token expiry date | Likely to be introduced as a standard extensionMaintains seperation of application layersAll Commercial Of the Shelf Products Support This Currently in use by the CMA9. |  

The oauth 2.0 introspction endpoint provides the ability to introspect tokens of all types! Forgerock and Ping support this out of the box so technically the majority of the Banks have this service for free. https://tools.ietf.org/html/rfc7662 the introspection endpoint is advertised on the well known.

**Comment by JamesMBligh** [comment]
Thanks for the feedback @ralphbragg-ob, the support for the introspection end point to obtain the status and expiry of the refresh token is expected.  I am currently collating previous feedback for the Authorisation End Points proposal and this will include this usage.  This is aligned to what is currently on the [InfoSec profile here](https://consumerdatastandardsaustralia.github.io/infosec/#13-7-introspection-endpoint).

I have included the additional fields on the authorisation response as we have to extend this for the concept of a "Sharing ID" anyway to support the ACCC rules around renewal, revocation notification and forced expiry of consent.  Since we were extending the response anyway the additional field will make things easier for the clients.  For the End Point proposal I am also considering the inclusion of the ability to introspect the "Sharing ID" even though it isn't actually a token.  This is not a firm position but it is something that I would like to obtain feedback on.

-JB-

**Comment by JamesMBligh** [comment]
Note that after discussion with the CX stream I have re-introduced the payee scope as a separate scope from regular payments.  This will be used for the payee end points (basic and detailed).  Multiple stakeholders have provided this feedback to both the API and CX streams.

The document in the main comment has been updated accordingly.

-JB-

**Comment by JamesMBligh** [comment]
I have realised that I inadvertently left out the ability to obtain the sharing ID and sharing expiry time for the token end point.  The sharing ID is required as it will facilitate ability to meet the requirements of the ACCC rules via the revocation and reauthorisation end points.

I have updated the document in the main comment accordingly.

-JB-

**Comment by assem-ali** [comment]
Hi James,
How would the data recipient specify to the data holder the required date range for the transactions?
for example, the data recipient may require transactions for the last 6 months, and continue to obtain transactions for the next 12 months for a particular use case.

**Comment by krishna1c** [comment]
Hi James
As part of proposal, it is mentioned that shared_duration will be sent as parameter. 
Is it better to add this parameter as custom claim in request object?

Thanks
Vamsi

**Comment by JamesMBligh** [comment]
@assem-ali, historic transactions would be filtered by query parameter using the various transaction end points. The maximum extent you could go back is defined by non-functional requirements and is not planned to be modifiable as part of the consent process.

The duration of the granted consent would be specified by the new *sharing_duration* parameter at the time consent is established. This can then be extended via the reauthorisation process.

-JB-

**Comment by JamesMBligh** [comment]
@krishna1c, we did look at using a new claim as an option for duration as well as the possibility of a set of scopes as well.

In the end we went with a new parameter as it seemed the least impactful on the standard and also the easiest to change away from in the future if a better option presents. Scopes and claims both have real meaning in OIDC and neither of these meanings really apply to the concept of consent duration. As such we would not only have been adding an extension to the standard (all three options would require non-standard build by the data holders) but we would have been changing the conceptual use of an existing part of the standard.

In light of this the additional parameter seems to be the lowest impact approach and also the approach the OAuth 2 standard would seem to cater for (based on some of the language around provider extensions to responses and requests in the various RFCs).

-JB-

**Comment by assem-ali** [comment]
> @assem-ali, historic transactions would be filtered by query parameter using the various transaction end points. The maximum extent you could go back is defined by non-functional requirements and is not planned to be modifiable as part of the consent process.
> 
> The duration of the granted consent would be specified by the new _sharing_duration_ parameter at the time consent is established. This can then be extended via the reauthorisation process.
> 
> -JB-
Thanks James. I might be missing something here:
This for me will not enable the data holder to adhere to the data minimisation principle in alignment with the customer consent (i.e.) if the customer consents for sharing transactions only for one month in the future, the entire history of transactions will be available for retrieval by the data recipient, which the customer has not consented for.

**Comment by JamesMBligh** [comment]
> Thanks James. I might be missing something here:
> This for me will not enable the data holder to adhere to the data minimisation principle in alignment with the customer consent (i.e.) if the customer consents for sharing transactions only for one month in the future, the entire history of transactions will be available for retrieval by the data recipient, which the customer has not consented for.

A couple of points:

1. The scope for banking transactions and the associated CX provided language addresses the intent that this scope allows for the recipient to obtain historic transactions once consent is granted.  There is nothing in the rules or the standards currently to limit the extent of the historic transactions for a specific consent.  The restrictions on duration of consent apply to the period of time that the recipient can make a valid CDR data request, not the extent of data available under that request.
1. The data minimisation principle only applies to the data recipient, not the data holder.  Refer to the data minimisation section under rule 1.7 of the exposure draft.  The section is copied below for ease:

> **data minimisation principle**: an accredited person complies with the data minimisation principle if:
(a) when making consumer data requests on behalf of a CDR consumer, the accredited person does not collect more CDR data than is reasonably needed in order to provide goods or services under a CDR contract; and
(b) when using CDR data that is collected under such requests, the accredited person does not use the CDR data beyond what is reasonably needed in order to provide goods or services under a CDR contract.

**Comment by spikejump** [comment]
Hi James,

The OIDC spec has expires_in field for Access Token defined as OPTIONAL.  I may have missed where CDR spec makes this attribute a mandatory one.  The decision proposal does not seem to call this out.  Assume this needs to be called out?  or we don't need this field as the Access Token MUST expires in 10 minutes so it is assumed by Holder and Recipients?

Thanks.

**Comment by spikejump** [comment]
Hi James,

There might be a typo in the decision proposal for sharing_duration.  It is currently specified 

"If the sharing_duration value is not a positive integer or zero then the authorisation should
fail."

However, value of zero also means one off access is requested in the line above.  Please clarify which behaviour zero is meant to imply.

Thanks.

**Comment by spikejump** [comment]
Sorry.  Another question:

The Claims as specified in the decision proposal presents a list of MUST be supported claims.  It says the list includes the OIDC claims.  However, several OIDC mandatory claims are not included in the list.  Assume this is an accident?  The missing ones are iss, aud, exp and iat for ID Token.

Thanks.

**Comment by WestpacOpenBanking** [comment]
#### Use of a consent object

Westpac does not recommend omitting the account request object. Doing so has these negative side effects (in order of severity):
1.	There is no mechanism of exchanging the consent purpose, consent start date, consent period and consent type as in Data61's CX Phase 2 prototypes nor extensibility for future rule or standard requirements (e.g a historic transaction limit [as described](https://github.com/ConsumerDataStandardsAustralia/standards/issues/64#issuecomment-489806331) by @assem-ali). 
2.	It is not possible for a Data Recipient to enquire on the status of an in-progress consent authorisation. For example, they will not know the difference between when a customer has not yet completed the authorisation and when a redirect error has occurred and the access token has not been returned to the third party.
3.	For long-lived consent, it is not possible for the Data Recipient to obtain rich status information, such as the reason for revocation, or an error status. The only data returned is whether the consent is active or not and it's expiry.
4.	If an invalid set of scopes is requested by the Data Recipient then it becomes a user-facing error due to the consents being validated in the front channel, rather than back channel.
5.	Ties the lifecycle of the refresh token to the lifecycle of the consent authorisation thereby reducing the ability to adapt to future needs.
•	For example, suppose the rules are updated to be more aligned to a typical bank's policy on token lifespan. That is, the new rule is that authorisations are valid for 12 months, however if a Customer has not used a Data Recipient's service for three months then the authorisation is deemed to have lapsed. This would imply that refresh tokens expire in three months and that refresh tokens are reissued every three months, as long as the Customer has logged into the Data Recipient's service during that period, up to a maximum of twelve months. While this can be implemented with the described flow, there is no way to communicate to the Data Recipient when the original 12 month authorisation expires.
6.	Lack of an explicit consent resource means that business information (e.g. consent purpose, consent start date, consent period, consent type, etc.) needs to be transmitted through security infrastructure. This will lead to a less secure system as neither Data Holders nor Data Recipients will be able to purchase and install security products (e.g. Identity and Access Management solution for Data Holders, certified OIDC and OAuth client libraries for Data Recipients) without customising them to deal with the custom claims required to transmit the required information.
7.	Potentially, the system will not be compatible with older browsers such as IE10 and below due to the large request objects generated by a long list of scopes.
8.	Potentially, there will be edge cases where the Data Holder needs to know whether the Data Recipient is retrying a previous a previous request or trying to create a new request. As the creation step is implicit, there is no way of determining this.

#### Naming of scopes

1.   Consideration should be given to how scopes are named with an eye to the future. Noting that initially there is only one, highest level of accreditation. Lower levels of accreditation may require reduced data sets and/or masked data to be returned from the same endpoints. The use of "basic" in the naming convention could be confusing if it ends up implying a higher level of access.

Key Management

This proposal should include key management details. Namely:
 
* Specification of the keys used to sign and encrypt the ID Token issued to Data Recipients.
* Information about the signing of access tokens issued to Data Recipients
* How signing/encryption key revocation is handled.

**Comment by ralphbragg-ob** [comment]
Hi James,

As I understand it, not everything is going in a signed request?  i the consent request duration being tacked in as a querystring parameter? Then this can be tampered with in the untrusted redirect through the user agent.

This is why I highly recommend that everything go in the request object or/ and that this resource is given its own data api.

RB






________________________________

**Comment by JamesMBligh** [comment]
Thanks @ralphbragg-ob, this is my oversight.  My intention was that this parameter would go in the request object as the `cdr_consent_id` field previously did.  I will correct the document and republish accordingly later today.

**Comment by JamesMBligh** [comment]
Hi @spikejump,

> The OIDC spec has expires_in field for Access Token defined as OPTIONAL. I may have missed where CDR spec makes this attribute a mandatory one. The decision proposal does not seem to call this out. Assume this needs to be called out? or we don't need this field as the Access Token MUST expires in 10 minutes so it is assumed by Holder and Recipients?

It doesn't call it out and I don't believe the intent is to make it mandatory, although we can if there is a good reason.  Please post if you have a justification. The expiry times for refresh token and sharing are mandatory as there are specific reasons for them to be provided.

-JB-

**Comment by JamesMBligh** [comment]
Hi @spikejump, 

> There might be a typo in the decision proposal for sharing_duration. It is currently specified
> 
> "If the sharing_duration value is not a positive integer or zero then the authorisation should
> fail."
> 
> However, value of zero also means one off access is requested in the line above. Please clarify which behaviour zero is meant to imply.

This wasn't a typo, more bad grammar.  The double negative makes the meaning confusing.  I have updated the document to reflect the intent which is:

`If the sharing_duration value is negative then the authorisation should fail`

The updated document with this change and the amendment recommended by @ralphbragg-ob to include `sharing_duration` in the request object has been updated on the main comment.

-JB-

**Comment by JamesMBligh** [comment]
Hi @spikejump,

> Sorry. Another question:

Don't be sorry, these are great questions ;)

> The Claims as specified in the decision proposal presents a list of MUST be supported claims. It says the list includes the OIDC claims. However, several OIDC mandatory claims are not included in the list. Assume this is an accident? The missing ones are iss, aud, exp and iat for ID Token.

I believe these are stated as being required in the JWT used for client authentication.  This is in the Client & Customer Authentication Proposal at #61.

-JB-

**Comment by JamesMBligh** [comment]
Hi @WestpacOpenBanking, responses inline...

> #### Use of a consent object
> Westpac does not recommend omitting the account request object. Doing so has these negative side effects (in order of severity):
> 
> 1. There is no mechanism of exchanging the consent purpose, consent start date, consent period and consent type as in Data61's CX Phase 2 prototypes nor extensibility for future rule or standard requirements (e.g a historic transaction limit [as described](https://github.com/ConsumerDataStandardsAustralia/standards/issues/64#issuecomment-489806331) by @assem-ali).

It is expected that consent purpose and type (where needed by the holder) would be static language provided from the Register.  Consent start is defined by the completion of the consent process.  Consent period is the new Sharing Duration component of the request object.

> 2. It is not possible for a Data Recipient to enquire on the status of an in-progress consent authorisation. For example, they will not know the difference between when a customer has not yet completed the authorisation and when a redirect error has occurred and the access token has not been returned to the third party.

The consent process has been limited to 5 minutes.  It is not a long running process so the need for introspection during consent is minimal.  It is also not a standard feature of OAuth 2 or OIDC.  If a customer chooses to abandon or reject the consent during the process with the holder then there is no obligation for their reasons to be made transparent to the recipient.

> 3. For long-lived consent, it is not possible for the Data Recipient to obtain rich status information, such as the reason for revocation, or an error status. The only data returned is whether the consent is active or not and it's expiry.

There is no obligation to communicate the Customer's reasons for revocation and the Customer may not wish this information to be requested or communicated.  With regard to error status, what sort of errors are being referred to?

> 4. If an invalid set of scopes is requested by the Data Recipient then it becomes a user-facing error due to the consents being validated in the front channel, rather than back channel.

Yes, but this is a systemic issue for the recipient rather than a transactional issue.  There are only seven scopes in the regime so I would not expect this to be a serious problem.  If it does we can apply a treatment such as the requirement to silently ignore invalid scopes for instance.  Do you think this case should be addressed now?

> 5. Ties the lifecycle of the refresh token to the lifecycle of the consent authorisation thereby reducing the ability to adapt to future needs.
>    •	For example, suppose the rules are updated to be more aligned to a typical bank's policy on token lifespan. That is, the new rule is that authorisations are valid for 12 months, however if a Customer has not used a Data Recipient's service for three months then the authorisation is deemed to have lapsed. This would imply that refresh tokens expire in three months and that refresh tokens are reissued every three months, as long as the Customer has logged into the Data Recipient's service during that period, up to a maximum of twelve months. While this can be implemented with the described flow, there is no way to communicate to the Data Recipient when the original 12 month authorisation expires.

The introduction of the Sharing ID and associated expiry time specifically addresses this issue.  It disconnects the refresh token from the lifespan of the refresh token.  I note that CBA requested that refresh tokens be specifically tied to the lifespan of the consent so this is something where a middle position between multiple viewpoints is required.

> 6. Lack of an explicit consent resource means that business information (e.g. consent purpose, consent start date, consent period, consent type, etc.) needs to be transmitted through security infrastructure. This will lead to a less secure system as neither Data Holders nor Data Recipients will be able to purchase and install security products (e.g. Identity and Access Management solution for Data Holders, certified OIDC and OAuth client libraries for Data Recipients) without customising them to deal with the custom claims required to transmit the required information.

I think I addressed this in the first point.

> 7. Potentially, the system will not be compatible with older browsers such as IE10 and below due to the large request objects generated by a long list of scopes.

There are seven scopes for the whole regime at the moment and only five of them are bank specific.  This would indicate that we have some headroom before this is a problem.  We may find that IE10 is less used by the time we have incorporated enough industries to make this a problem. 

> 8. Potentially, there will be edge cases where the Data Holder needs to know whether the Data Recipient is retrying a previous a previous request or trying to create a new request. As the creation step is implicit, there is no way of determining this.

Some expansion of these edge cases would be of value.  There may be other mechanisms we could use to accommodate this.  One way would be to specifically state that a new consent initiation will automatically invalidate any other in flight consent processes or we could state that new consent initiations should be rejected if one is already in flight.  This might be something valuable to explore further.

> #### Naming of scopes
> 1. Consideration should be given to how scopes are named with an eye to the future. Noting that initially there is only one, highest level of accreditation. Lower levels of accreditation may require reduced data sets and/or masked data to be returned from the same endpoints. The use of "basic" in the naming convention could be confusing if it ends up implying a higher level of access.

None of the scopes relate to accreditation, only to data clusters.  "basic" refers to basic information about a resource such as an account or customer record.  Accreditation levels for recipients would be communicated in the meta data from the ACCC Register.  At most there may be a future scenario where certain accreditation levels results in a subset of scopes being available to a recipient but this is not certain.

We have used the banking and customer prefixes on the scopes to facilitate holder specific scopes (prefixed with a holder ID of some sort) or future designated industries.

> #### Key Management
> This proposal should include key management details. Namely:
> 
> * Specification of the keys used to sign and encrypt the ID Token issued to Data Recipients.
> * Information about the signing of access tokens issued to Data Recipients
> * How signing/encryption key revocation is handled.

These items are to be specified by the design of the ACCC Register.

-JB-

**Comment by dpostnikov** [comment]
Hi James, what is the benefit of not having Consent API (account request / intent )? 

It provides a lot of flexibility going forward in regards to data attributes and use cases supported.

**Comment by JamesMBligh** [comment]
Hi @dpostnikov, the consent API isn’t standard. It would be an extension to OAuth 2 and OIDC. This means that it increases the cost of compliance for both recipients and holders.  It is also not currently needed as the CX testing identified that scopes would be sufficient for customers in understanding consent.

It is also something we can add in later if there is a need. That also has the advantage of adding it to solve a real problem rather than a possible abstract future problem. The fact we haven’t added it does not reduce our flexibility as we can always add it later.

-JB-

**Comment by commbankoss** [comment]
Commonwealth Bank has the following recommendations and comments regarding Decision Proposal 64:
 
1.      Commonwealth Bank recommends a dedicated consent resource API to manage consent metadata (e.g. sharing duration) rather than stretching the use of standard OIDC calls to incorporate this concept. A dedicated consent resource API will provide additional flexibility to futureproof the ecosystem and allow all consent metadata to be passed via backchannels.
 
2.      Commonwealth Bank recommends the adoption of a 1:1 relationship between ‘scopes’ and ‘endpoints’. This will give greater flexibility and granularity for managing access to data resources as new use-cases appear.
 
3.      We seek further clarity regarding the scenarios in which the ID Token exposes ‘first name/last name’.
 
4.      We support Westpac’s comments on GitHub on this Decision Proposal and also require more clarity regarding Key Management. 
 
5.       Commonwealth Bank supports the comments made by @ralphbragg-ob on GitHub recommending the use of Token Introspection endpoint to communicate token expiry, rather than the creation of additional custom scopes.
 
6.     Finally, Commonwealth Bank notes in the Scopes that basic_bank_accounts explicitly excludes account identifiers, however as account identifiers are used in the URI for other end points, e.g. transactions, this would appear to render the bank_transactions scope unworkable, as no identifiers are supplied. We recommend that security scopes not change the set of mandatory fields included in an API response.

**Comment by anzbankau** [comment]
Hi James,

Feedback below:
•	refresh_token_expires_in refers to "This field MUST specify the expiration time in seconds from the time of the request for the refresh token supplied.” 
We believe this is from the time of authorization code grant to get refresh and access token. Appreciate further clarity in standards.
•	Refresh Token - If refresh_token is set to min validity of 28 days by Data Holder with consent >  28 days (e.g. 12months) - Is the expectation that new consent need to be established with customer to resume access data? 
•	Related to above - If Refresh token cycling extends validity of refresh token then there is still a case where infrequent access by data recipient can lead to expiry of refresh token and need to establish consent again with customer. We’ll appreciate standards to call out these behaviors related to refresh token lifecycle. 

Thanks.

**Comment by NationalAustraliaBank** [comment]
**Tokens**
- NAB seeks clarity for how joint account authorisations will work for once-off sharing requests where they were not pre-authorised by account holders, given 10 minute access token expiry with no refresh token.
- The _refresh_token_expires_in_ field returned on the token endpoint is not a standard OAUTH response field and is not required given that there is a token introspection endpoint which can be used to determine refresh token expiry. We recommend the removal of _refresh_token_expires_in_ from the specification.

**Consent API and Sharing ID**
Overall, it appears that the proposed approach tries to avoid the creation of the consent endpoint at a cost of over-complicating and customising the standard OAUTH protocol. Specifically:
- We note that the sharing ID is a non-standard extension to OAUTH / OIDC protocols and it couples the security endpoints (_token_endpoint_) with the business concerns which is the consent metadata. We agree with [Westpac's comment](https://github.com/ConsumerDataStandardsAustralia/standards/issues/64#issuecomment-490348714) on this topic.
- The request sharing duration is a customisation of the protocol which can be addressed by having a separate consent endpoint.
- It would be more appropriate to use a separate endpoint to create and request consent authorisation metadata (similar to the consent endpoint as per UK specifications). This will provide a simpler interface that separates the consent endpoint and related business concerns from the token endpoint and security concerns.

**Scopes**
- As previously stated in [our comment](https://github.com/ConsumerDataStandardsAustralia/standards/issues/39#issuecomment-441159032) on Decision Proposal 39, NAB is still not supportive of providing Personally Identifiable Information (PII) and other sensitive data. A more granular set of scopes should be further analysed, in particular for the customer's transaction data. A customer may not be fully aware of the data they are sharing and its consequences.

**Comment by JamesMBligh** [comment]
Feedback to @commbankoss:

> 1. Commonwealth Bank recommends a dedicated consent resource API to manage consent metadata (e.g. sharing duration) rather than stretching the use of standard OIDC calls to incorporate this concept. A dedicated consent resource API will provide additional flexibility to futureproof the ecosystem and allow all consent metadata to be passed via backchannels.

This feedback was considered when the consent API was removed.  The current proposal is considered a more minimal modification of the standards and done in a way that the standard andards explicitly accommodate.  The use of a consent API is not off the table for future use, only for version 1 as there is no clear functional driver to include it.

> 2. Commonwealth Bank recommends the adoption of a 1:1 relationship between ‘scopes’ and ‘endpoints’. This will give greater flexibility and granularity for managing access to data resources as new use-cases appear.

This is new feedback and doesn’t accommodate the findings of the CX workstream or the way Customers understand their data. Some end points, for instance provide the exact data of other end points but simply use different filtering.  It is unclear what the tangible benefits are of this change would be.

> 3. We seek further clarity regarding the scenarios in which the ID Token exposes ‘first name/last name’.

The ID Token should include additional claims if the Customer endorses consent and the consent request includes the name claims.  The ID Token should only include these claims if provided via the token end point, however, no through the Authorise end point.

> 5. Commonwealth Bank supports the comments made by @ralphbragg-ob on GitHub recommending the use of Token Introspection endpoint to communicate token expiry, rather than the creation of additional custom scopes.

This is the position of the proposal so there would appear to be a change required here.

> 6. Finally, Commonwealth Bank notes in the Scopes that basic_bank_accounts explicitly excludes account identifiers, however as account identifiers are used in the URI for other end points, e.g. transactions, this would appear to render the bank_transactions scope unworkable, as no identifiers are supplied. We recommend that security scopes not change the set of mandatory fields included in an API response.

Account identifiers, in this context, refers to identifiers that the Customer would use, not the ID provided within the CDR specification.  This specifically refers to Account BSB and Number.  The rules around ID permanence that ensure that the CDR Account ID is unusable outside of the context of the specific consent arrangement is specifically included to ensure the various ID fields in the CDR standard of no value if leaked.

-JB-

**Comment by JamesMBligh** [comment]
Feedback to @anzbankau:

> •	refresh_token_expires_in refers to "This field MUST specify the expiration time in seconds from the time of the request for the refresh token supplied.”
> We believe this is from the time of authorization code grant to get refresh and access token. Appreciate further clarity in standards.

This field is modeled on the expires_in field for the Access Token.  Both fields contain the number of seconds to expiry from the time of the call to the end point, not to the time of token creation.  Hope this clarifies.

> •	Refresh Token - If refresh_token is set to min validity of 28 days by Data Holder with consent > 28 days (e.g. 12months) - Is the expectation that new consent need to be established with customer to resume access data?

The expectation is that, if the refresh_token is set to an expiry less than the consent then a new refresh_token should be provided whenever a new Access Token is provided.  I’ll add this in to make it clear.

> •	Related to above - If Refresh token cycling extends validity of refresh token then there is still a case where infrequent access by data recipient can lead to expiry of refresh token and need to establish consent again with customer. We’ll appreciate standards to call out these behaviors related to refresh token lifecycle.

That is correct.  I will add a statement making this clear to recipients.  As a session can be established unattended then this can be controlled and managed by the recipient.

-JB-

**Comment by JamesMBligh** [comment]
Feedback to @NationalAustraliaBank:

> **Tokens**
> 
> * NAB seeks clarity for how joint account authorisations will work for once-off sharing requests where they were not pre-authorised by account holders, given 10 minute access token expiry with no refresh token.

In this scenario the account that has not been jointly authorised would be inaccessible during the extent of consent arrangement.

> * The _refresh_token_expires_in_ field returned on the token endpoint is not a standard OAUTH response field and is not required given that there is a token introspection endpoint which can be used to determine refresh token expiry. We recommend the removal of _refresh_token_expires_in_ from the specification.

It has been included to simplify refresh token cycling which is something requested by holders and there has not been an indication that providing the field is difficult.  Removing it would force recipients to perform an introspection call every time an access token is obtained as they would not be able to assume the refresh token expiry and they would risk expiration of the refresh token if they do not obtain the expiry time.  Forcing this extra traffic systemically is considered a negative orphan removing the field.

> **Consent API and Sharing ID**
> Overall, it appears that the proposed approach tries to avoid the creation of the consent endpoint at a cost of over-complicating and customising the standard OAUTH protocol. Specifically:
>
> * We note that the sharing ID is a non-standard extension to OAUTH / OIDC protocols and it couples the security endpoints (_token_endpoint_) with the business concerns which is the consent metadata. We agree with [Westpac's comment](https://github.com/ConsumerDataStandardsAustralia/standards/issues/64#issuecomment-490348714) on this topic.

The token and introspection end points already incorporate the concept of expiration.  The sharing expiry is entirely aligned with this usage.  It is unclear why the expiration of the consent as a whole and the expiration of a specific token should be conceptually separated in the manner suggested.

> * The request sharing duration is a customisation of the protocol which can be addressed by having a separate consent endpoint.

Both options are customisations.  The consent API is a more significant customisation and still requires the consent ID to be added to the request object of the Authorise end point.

> * It would be more appropriate to use a separate endpoint to create and request consent authorisation metadata (similar to the consent endpoint as per UK specifications). This will provide a simpler interface that separates the consent endpoint and related business concerns from the token endpoint and security concerns.

This is a subjective assessment that I don’t believe is accurate.  It could just as easily be argued that a consent API overrides the standard usage of scopes and claims in the normative standard and the provides a secondary mechanism for the same information.  If a consent object created by the consent API has different information to the Authorise request object then which of the two should be considered valid?  If the use of a consent API was a prima facie superior design choice then it would probably be included in OAuth, OIDC or FAPI.

> **Scopes**
> 
> * As previously stated in [our comment](https://github.com/ConsumerDataStandardsAustralia/standards/issues/39#issuecomment-441159032) on Decision Proposal 39, NAB is still not supportive of providing Personally Identifiable Information (PII) and other sensitive data. A more granular set of scopes should be further analysed, in particular for the customer's transaction data. A customer may not be fully aware of the data they are sharing and its consequences.

This feedback was preciously acknowledged and has already been accommodated as far as the evidence obtained through CX testing has indicated is appropriate.

As for the inclusion of PII data, the standards are aligned with the requirements of CDR rules and the designation instrument.

Hope all that makes sense.

-JB-

**Comment by JamesMBligh** [comment]
The proposal has been amended in the main comment to accommodate the changes accepted in previous comments.

This issue has now been locked and a final decision document will be drafted for consideration by the Chair.

**Comment by JamesMBligh** [comment]
Please find attached the final decision covering this issue
[Decision 061-066,068 - Information Security Profile.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/3251480/Decision.061-066.068.-.Information.Security.Profile.pdf)
