### ISSUE TITLE
access token revocation text is self-contradictory

### ISSUE THREAD

**Issue by rfc6919** [ConsumerDataStandardsAustralia/standards#75]
https://consumerdatastandardsaustralia.github.io/standards/?shell#requirements-for-data-recipient-implementations

"Revocation of Access Tokens MUST be not be supported"

**Comment by CDR-API-Stream** [comment]
Hi @rfc6919 - as per previous comment (https://github.com/ConsumerDataStandardsAustralia/standards/issues/74#issuecomment-511073602) I will copy this comment to the open thread and close this issue.
