### ISSUE TITLE
Decision Proposal 76 - Authorisation Flow

### ISSUE THREAD

**Issue by CDR-InfoSec-Stream** [ConsumerDataStandardsAustralia/standards#76]
This thread has been created to publish the decision relating to the Authorisation Flow to be adopted for the initial CDR implementation.

The decision paper is pending approval by the Chair but is intended to be published on the 15th July.

**Comment by CDR-API-Stream** [comment]
Please find attached the approved decision regarding Authorisation Flow.
[Decision 76 - Authorisation Flow.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/3390517/Decision.76.-.Authorisation.Flow.pdf)

Note that a decision regarding re-authorisation has been deferred pending additional consultation with the regulator and the community.  In the interim the assumption for implementation is that re-authorisation would require the authorisation flow to be executed again in entirety.
