### ISSUE TITLE
Decision Proposal 78 - Independent Information Security Review

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#78]
As stated in various forums the Data Standards Body has commissioned an independent review of the Information Security Profile contained in the May 2019 draft of the standards.

This review has been conducted by Fortian (https://fortian.com.au/).

The final report arising from this review, along with a decision paper outlining changes to the standards in response to the report will be published in this thread.

**Comment by perlboy** [comment]
Please publish the scope statement (ie. the RFP) given to Fortian as part of their engagement.

**Comment by CDR-API-Stream** [comment]
Please find attached the report provided by Fortian generated by the review they conducted.  Note that the brief for the review is reiterated within the report.
[Consumer_Data_Right_Security_Review_Final.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/3401837/Consumer_Data_Right_Security_Review_Final.pdf)

**Comment by CDR-API-Stream** [comment]
Please find attached the decision, endorsed by the Chair, containing responses to the recommendations to the content of the report arising from the independent information security review.
[Decision 078 - Independent Information Security Review.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/3401842/Decision.078.-.Independent.Information.Security.Review.pdf)
