### ISSUE TITLE
Clarification on x-v header usage

### ISSUE THREAD

**Issue by andreww112** [ConsumerDataStandardsAustralia/standards#81]
Hi, I've been told this is the place to ask technical questions about the standards...

I have a question about the x-v (and x-min-v) header in the API.

The route/path gives the version of the CDR (/v1/), then the header value x-v gives us the int version of the API within that (effectively the minor version)

Currently the version released is 0.9.6, what x-v release is that?

**Comment by CDR-API-Stream** [comment]
Hi @andreww112 , in this repo we request that new issues are not created and that comments are added to existing threads instead.  This is not standard GitHub issues practice but is needed in our case as it aligns with the decision making process for the regime.

This comment will be reposted in the existing open thread and response will be provided there.

This issue will be closed.
