### ISSUE TITLE
"BankingTransaction" Schema

### ISSUE THREAD

**Issue by drewbroadfoot** [ConsumerDataStandardsAustralia/standards#82]
Apologies if I'm not doing this correctly, but I'm not a programmer, and I'm a little out of my depth.

The way I read the Standards, I see that the following "BankingTransaction" properties are listed as optional. 

- merchantName
- merchantCategoryCode
- billerCode
- billerName
- crn
- apcaNumber

According to RFC 2119:

5. MAY   This word, or the adjective "OPTIONAL", mean that an item is
   truly optional.  One vendor may choose to include the item because a
   particular marketplace requires it or because the vendor feels that
   it enhances the product while another vendor may omit the same item.

From the above, it appears that the provision of the above listed properties is at the discretion of the data holder.  From my reading of Schedule 2, clause 1.3 of the Draft Rules, I thought this data would be mandatory.  

Please let me know if these properties will be changed to mandatory or conditional (provided if the data holder has them for a particular transaction).

Cheers

Drew

**Comment by drewbroadfoot** [comment]
I have changed this to be a comment on the issue seeking comments on the July working draft, which is where it belongs (I think).  Sorry if this caused any issues.

**Comment by CDR-API-Stream** [comment]
Thanks for moving the comment @drewbroadfoot.  No issues caused.  A response has been provided on issue 79
