### ISSUE TITLE
Encryption algorithm for ID Tokens

### ISSUE THREAD

**Issue by versent1Jas** [ConsumerDataStandardsAustralia/standards#88]
[This](https://consumerdatastandardsaustralia.github.io/standards/#tokens) section in Data61 spec specifies that ID tokens **must** be encrypted. However, the algorithm for encryption has not been defined. OIDC spec allows following to be used for encryption as specified [here](https://openid.net/specs/openid-connect-core-1_0.html#Encryption).
Can the algorithm be specified for assistance in implementation of encryption of ID tokens.

**Comment by CDR-API-Stream** [comment]
@versent1Jas, as per the comments in other threads and as articulated in the README, it would be appreciated if you could close this issue and raise you issue on the maintenance repository for consideration:
https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues

**Comment by versent1Jas** [comment]
Thanks, @CDR-API-Stream . Re-opening the query as directed.
