### ISSUE TITLE
x-cds-subject

### ISSUE THREAD

**Issue by s-wickham** [ConsumerDataStandardsAustralia/standards#91]
Hi,

I'm looking for more information on the header parameter 'x-cds-subject'.

Is this how the APIs are expected to deduce which customer's data the request is for, or is that customer's ID to be taken from the claims in the ID token/access token?

Thanks!

**Comment by CDR-API-Stream** [comment]
Hi @s-wickham.  For reference, queries should be submitted on the maintenance repository at:
https://github.com/ConsumerDataStandardsAustralia/standards-maintenance

On the specific question, the x-cds-subject is in the process of being removed from the standard as it is now deemed to be redundant (the subject can be determined by the Data Holder from the Access Token).

For more information refer to maintenance issue https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/33
