### ISSUE TITLE
Decision Proposal 097 - Principles Review

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#97]
In anticipation of the expansion of the CDR regime to additional sectors the DSB is initiating a review of the principles that guide the development of the CDR standards.

Attached is a decision proposal containing a number of suggested changes but all feedback related to the principles is welcome.

The consultation draft for this decision proposal is attached below:
[Decision Proposal 097 - Principles Review.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/4061829/Decision.Proposal.097.-.Principles.Review.pdf)

Feedback is now open for this proposal. Feedback is planned to be closed on the 29th February.

**Comment by CDR-API-Stream** [comment]
Consultation is now closed on this topic.  A revised proposal for principles will be issued in due course.

**Comment by Pelsurry** [comment]
API Development Principle 2 promulgates the adoption of open, widely used standards. The benefits of using open standards don’t need repeating here. It may be the intention, but can the principle be further clarified to point to globally accepted standards? Adhering to global standards, in line with the recommendations in the original Consumer Data Right report, has substantial benefits for consumers and the Australian industries captured under the Consumer Data Right. It can reduce implementation costs and complexity, lower entry barriers for new service providers and allow local developers to export their solutions to other regions. In the ongoing data standards discussions, it occasionally appears that the significant benefits of adhering to globally accepted standards are not given sufficient weight in decisions.

**Comment by WestpacOpenBanking** [comment]
We welcome the review of the principles that guide the development of the CDR standards. 

We agree that the standards should strive for consistency between sectors where it is beneficial and practical to do so. However, as discussed in the Energy Standards Development Framework noting paper, there are circumstances where this is not the right approach. We think that the principle should be more balanced and remark that consistency should be considered and to address the broad circumstances where standards divergence would be appropriate.

The technical principles are currently narrowly focused on the development of APIs and do not encompass other issues which the standards currently address including security and the technical management of the consent process. We suggest that principles may be considered on the following matters:

* That technical standards should support the rules as well as CX principles, research and standards. 
* Alignment of security standards to international standards
* Independent assessment of the security standards
* Boundaries between the standards and the ACCC registry specifications

We also remark that principles guiding standards development contain no requirements for ecosystem participants and hence need not be published as part of the standard itself. It may be better to publish them in a place appropriate to each standards development stream. For example, many participants involved in the development of the CX standards may only be familiar with the CX stream’s Medium site and it seems appropriate that the CX stream are responsible for maintaining and updating the CX Principles. 

Following on from the above, we recommend not attempting to restate the CX principle in an API principle. Suggested wording:

**Principle 3: APIs provide a good customer experience**
The API definitions will consider and incorporate the customer experience implications and facilitate the achievement of the CX principles.

**Comment by CDR-API-Stream** [comment]
Thanks for the feedback.  This consultation is now being closed.  A final decision will be published in due course.

**Comment by CDR-API-Stream** [comment]
The final decision on the modifications to the principles is below.  These changes will be incorporated into v1.3.0 of the standards.
[Decision 097 - Principles Review.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/4483915/Decision.097.-.Principles.Review.pdf)

Note that these principles will guide ongoing development of both technical and experience oriented standards but do not materially change the standards themselves.  This change therefore has no impact on existing or in-flight implementations.
